//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_Lecturas
    {
        public long IdLectura { get; set; }
        public int IdRegion { get; set; }
        public int IdLocalidad { get; set; }
        public int IdTerminal { get; set; }
        public long IdEmpleado { get; set; }
        public short TipoEntrada { get; set; }
        public Nullable<System.DateTime> FechaLectura { get; set; }
        public Nullable<System.TimeSpan> HoraLectura { get; set; }
        public Nullable<short> IdEstadoLectura { get; set; }
        public Nullable<short> ModoVerificacion { get; set; }
        public Nullable<short> WorkCode { get; set; }
        public Nullable<System.DateTime> FechaHoraEnvio { get; set; }
        public Nullable<short> IdZonaActual { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual EPK_Empleados EPK_Empleados { get; set; }
        public virtual EPK_Terminal EPK_Terminal { get; set; }
    }
}
