//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_GrupoZona
    {
        public EPK_GrupoZona()
        {
            this.EPK_TerminalGrupo = new HashSet<EPK_TerminalGrupo>();
        }
    
        public int IdRegion { get; set; }
        public short IdGrupo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<short> TipoVerificacion { get; set; }
        public Nullable<bool> FeriadosValidos { get; set; }
        public Nullable<short> IdZona1 { get; set; }
        public Nullable<short> IdZona2 { get; set; }
        public Nullable<short> IdZona3 { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual EPK_Region EPK_Region { get; set; }
        public virtual ICollection<EPK_TerminalGrupo> EPK_TerminalGrupo { get; set; }
    }
}
