//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_TipoDispositivo
    {
        public EPK_TipoDispositivo()
        {
            this.EPK_Dispositivo = new HashSet<EPK_Dispositivo>();
        }
    
        public short IdTipoDispositivo { get; set; }
        public string Descripcion { get; set; }
        public bool Unico { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual ICollection<EPK_Dispositivo> EPK_Dispositivo { get; set; }
    }
}
