//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_TipoPrenda
    {
        public EPK_TipoPrenda()
        {
            this.EPK_Grupo = new HashSet<EPK_Grupo>();
        }
    
        public byte IdTipoPrenda { get; set; }
        public string Descripcion { get; set; }
        public bool Ropa { get; set; }
        public bool RestriccionVenta { get; set; }
    
        public virtual ICollection<EPK_Grupo> EPK_Grupo { get; set; }
    }
}
