//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_MotivoDescuento
    {
        public EPK_MotivoDescuento()
        {
            this.EPK_AlivioEfectivoEncabezado = new HashSet<EPK_AlivioEfectivoEncabezado>();
        }
    
        public byte IdMotivoDesc { get; set; }
        public string Motivo { get; set; }
    
        public virtual ICollection<EPK_AlivioEfectivoEncabezado> EPK_AlivioEfectivoEncabezado { get; set; }
    }
}
