//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_NotaCreditoEncabezado
    {
        public EPK_NotaCreditoEncabezado()
        {
            this.EPK_NotaCreditoDetalle = new HashSet<EPK_NotaCreditoDetalle>();
            this.EPK_NotaCreditoEsperaEncabezado = new HashSet<EPK_NotaCreditoEsperaEncabezado>();
        }
    
        public int IdNotaC { get; set; }
        public int IdTienda { get; set; }
        public int IdFactura { get; set; }
        public short IdEstatus { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public decimal PorcDescuento { get; set; }
        public Nullable<decimal> MontoBase { get; set; }
        public Nullable<decimal> MontoDescuento { get; set; }
        public decimal MontoIVA { get; set; }
        public decimal MontoTotal { get; set; }
        public string TicketFiscal { get; set; }
        public string COO { get; set; }
        public string SerialMF { get; set; }
        public string Motivo { get; set; }
        public string Observacion { get; set; }
        public string NroReporteZ { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int IdUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
        public string NombreCliente { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual EPK_FacturaEncabezado EPK_FacturaEncabezado { get; set; }
        public virtual ICollection<EPK_NotaCreditoDetalle> EPK_NotaCreditoDetalle { get; set; }
        public virtual EPK_Tienda EPK_Tienda { get; set; }
        public virtual ICollection<EPK_NotaCreditoEsperaEncabezado> EPK_NotaCreditoEsperaEncabezado { get; set; }
    }
}
