//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_SeguridadPlantillaApp
    {
        public int IdPlantilla { get; set; }
        public int IdApp { get; set; }
        public int IdPerfil { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual EPK_App EPK_App { get; set; }
        public virtual EPK_Perfil EPK_Perfil { get; set; }
        public virtual EPK_SeguridadPlantilla EPK_SeguridadPlantilla { get; set; }
    }
}
