//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_UsuarioApp_BackupData
    {
        public int IdUsuario { get; set; }
        public int IdPerfil { get; set; }
        public int IdApp { get; set; }
        public Nullable<int> IdObjetoPrincipal { get; set; }
        public byte[] TStamp { get; set; }
    }
}
