//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_TemporadaGrupo
    {
        public int IdTemporada { get; set; }
        public int IdGrupo { get; set; }
        public Nullable<decimal> PorcentajeAumento { get; set; }
    
        public virtual EPK_Grupo EPK_Grupo { get; set; }
        public virtual EPK_Temporada EPK_Temporada { get; set; }
    }
}
