//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_ClienteCompra
    {
        public long IdVentaCliente { get; set; }
        public byte IdTipoDocumento { get; set; }
        public string NumeroDocumento { get; set; }
        public int IdArticulo { get; set; }
        public byte Cantidad { get; set; }
        public System.DateTime FechaUltAct { get; set; }
    
        public virtual EPK_Articulo EPK_Articulo { get; set; }
    }
}
