//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_CajaDispositivo
    {
        public int IdCajaDispositivo { get; set; }
        public int IdDispositivo { get; set; }
        public int IdCaja { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual EPK_Caja EPK_Caja { get; set; }
        public virtual EPK_Dispositivo EPK_Dispositivo { get; set; }
    }
}
