//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_Auditoria
    {
        public long IdAuditoria { get; set; }
        public int IdAPP { get; set; }
        public int IdUsuario { get; set; }
        public string AccionEjecutada { get; set; }
        public System.DateTime FechaEjecucion { get; set; }
        public string EventLevel { get; set; }
        public string IP { get; set; }
        public string Host { get; set; }
        public string Exception { get; set; }
        public byte[] TStamp { get; set; }
    }
}
