//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_TipoDocumento
    {
        public EPK_TipoDocumento()
        {
            this.EPK_Cliente = new HashSet<EPK_Cliente>();
        }
    
        public byte IdTipoDocumento { get; set; }
        public string Descripcion { get; set; }
        public string Sigla { get; set; }
        public bool PersonaNatural { get; set; }
        public bool Principal { get; set; }
        public string Validacion { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual ICollection<EPK_Cliente> EPK_Cliente { get; set; }
    }
}
