//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_EventoTerminal
    {
        public int IdRegion { get; set; }
        public int IdLocalidad { get; set; }
        public int IdTerminal { get; set; }
        public int IdEvento { get; set; }
        public Nullable<System.DateTime> FechaHoraEvento { get; set; }
        public string Mensaje { get; set; }
        public Nullable<System.DateTime> FechaHoraEnvio { get; set; }
        public Nullable<System.DateTime> FechaHoraEjecucion { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual EPK_Terminal EPK_Terminal { get; set; }
    }
}
