//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_FlujoEfectivo
    {
        public EPK_FlujoEfectivo()
        {
            this.EPK_FlujoEfectivoDetalle = new HashSet<EPK_FlujoEfectivoDetalle>();
        }
    
        public int IdFlujoEfectivo { get; set; }
        public int IdCaja { get; set; }
        public int IdUsuario { get; set; }
        public bool Cambio { get; set; }
        public decimal Total { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string Observacion { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual EPK_Caja EPK_Caja { get; set; }
        public virtual EPK_Usuario EPK_Usuario { get; set; }
        public virtual ICollection<EPK_FlujoEfectivoDetalle> EPK_FlujoEfectivoDetalle { get; set; }
    }
}
