//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_AlivioEfectivoDetalle
    {
        public long IdAlivioEfectivo { get; set; }
        public byte IdDenominacion { get; set; }
        public short CantidadCajero { get; set; }
        public Nullable<short> CantidadAprobador { get; set; }
    
        public virtual EPK_AlivioEfectivoEncabezado EPK_AlivioEfectivoEncabezado { get; set; }
        public virtual EPK_Denominacion EPK_Denominacion { get; set; }
    }
}
