//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_Region
    {
        public EPK_Region()
        {
            this.EPK_CombinacionGrupos = new HashSet<EPK_CombinacionGrupos>();
            this.EPK_EmpleadoAcceso = new HashSet<EPK_EmpleadoAcceso>();
            this.EPK_FeriadosRegion = new HashSet<EPK_FeriadosRegion>();
            this.EPK_GrupoZona = new HashSet<EPK_GrupoZona>();
            this.EPK_Localidad = new HashSet<EPK_Localidad>();
            this.EPK_Zonas = new HashSet<EPK_Zonas>();
        }
    
        public int IdRegion { get; set; }
        public string Descripcion { get; set; }
        public string CodigoPostal { get; set; }
        public Nullable<int> IdPais { get; set; }
        public Nullable<short> IdEstado { get; set; }
        public Nullable<short> IdCiudad { get; set; }
        public Nullable<short> IdTipoRegion { get; set; }
        public Nullable<bool> BonoAlimentacionExtra { get; set; }
        public Nullable<decimal> HorasBonoAlimentacionBasico { get; set; }
        public Nullable<int> IdTienda { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual ICollection<EPK_CombinacionGrupos> EPK_CombinacionGrupos { get; set; }
        public virtual ICollection<EPK_EmpleadoAcceso> EPK_EmpleadoAcceso { get; set; }
        public virtual ICollection<EPK_FeriadosRegion> EPK_FeriadosRegion { get; set; }
        public virtual ICollection<EPK_GrupoZona> EPK_GrupoZona { get; set; }
        public virtual ICollection<EPK_Localidad> EPK_Localidad { get; set; }
        public virtual EPK_Pais EPK_Pais { get; set; }
        public virtual EPK_TipoRegion EPK_TipoRegion { get; set; }
        public virtual ICollection<EPK_Zonas> EPK_Zonas { get; set; }
    }
}
