//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_TipoTienda
    {
        public EPK_TipoTienda()
        {
            this.EPK_Tienda = new HashSet<EPK_Tienda>();
            this.EPK_TipoTiendaFormaPago = new HashSet<EPK_TipoTiendaFormaPago>();
        }
    
        public short IdTipoTienda { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] TStamp { get; set; }
        public bool AplicaImpuesto { get; set; }
    
        public virtual ICollection<EPK_Tienda> EPK_Tienda { get; set; }
        public virtual ICollection<EPK_TipoTiendaFormaPago> EPK_TipoTiendaFormaPago { get; set; }
    }
}
