//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_Localidad
    {
        public EPK_Localidad()
        {
            this.EPK_EmpleadoLocalidad = new HashSet<EPK_EmpleadoLocalidad>();
        }
    
        public int IdLocalidad { get; set; }
        public int IdRegion { get; set; }
        public string Descripcion { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual ICollection<EPK_EmpleadoLocalidad> EPK_EmpleadoLocalidad { get; set; }
        public virtual EPK_Region EPK_Region { get; set; }
    }
}
