//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_Log_Sesiones
    {
        public System.DateTime FechaHora { get; set; }
        public string IdUsuario { get; set; }
        public int IdPaginaUsuario { get; set; }
        public string Operacion { get; set; }
        public byte[] TStamp { get; set; }
    }
}
