//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_Denominacion
    {
        public EPK_Denominacion()
        {
            this.EPK_AlivioEfectivoDetalle = new HashSet<EPK_AlivioEfectivoDetalle>();
            this.EPK_AperturaCajeroDenominacion = new HashSet<EPK_AperturaCajeroDenominacion>();
            this.EPK_CierreCajeroDenominacion = new HashSet<EPK_CierreCajeroDenominacion>();
            this.EPK_DepositoDetalle = new HashSet<EPK_DepositoDetalle>();
            this.EPK_EfectivoRemanenteDetalle = new HashSet<EPK_EfectivoRemanenteDetalle>();
            this.EPK_FlujoEfectivoDetalle = new HashSet<EPK_FlujoEfectivoDetalle>();
        }
    
        public byte IdDenominacion { get; set; }
        public decimal Denominacion { get; set; }
        public bool Billete { get; set; }
        public byte[] Logo { get; set; }
        public string MimeType { get; set; }
        public string FileName { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual ICollection<EPK_AlivioEfectivoDetalle> EPK_AlivioEfectivoDetalle { get; set; }
        public virtual ICollection<EPK_AperturaCajeroDenominacion> EPK_AperturaCajeroDenominacion { get; set; }
        public virtual ICollection<EPK_CierreCajeroDenominacion> EPK_CierreCajeroDenominacion { get; set; }
        public virtual ICollection<EPK_DepositoDetalle> EPK_DepositoDetalle { get; set; }
        public virtual ICollection<EPK_EfectivoRemanenteDetalle> EPK_EfectivoRemanenteDetalle { get; set; }
        public virtual ICollection<EPK_FlujoEfectivoDetalle> EPK_FlujoEfectivoDetalle { get; set; }
    }
}
