//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_Lenguaje
    {
        public EPK_Lenguaje()
        {
            this.EPK_Organizacion = new HashSet<EPK_Organizacion>();
        }
    
        public string IdLenguaje { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual ICollection<EPK_Organizacion> EPK_Organizacion { get; set; }
    }
}
