//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_TipoRegion
    {
        public EPK_TipoRegion()
        {
            this.EPK_Region = new HashSet<EPK_Region>();
        }
    
        public short IdTipoRegion { get; set; }
        public string Descripcion { get; set; }
        public bool BonoAliBaseFraccionado { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual ICollection<EPK_Region> EPK_Region { get; set; }
    }
}
