//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_ActualizacionColeccion
    {
        public int IdActualizacion { get; set; }
        public int IdColeccion { get; set; }
        public bool Activa { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual EPK_ActualizacionEncabezado EPK_ActualizacionEncabezado { get; set; }
        public virtual EPK_Coleccion EPK_Coleccion { get; set; }
    }
}
