//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_HistoricoFacturaEncabezado
    {
        public EPK_HistoricoFacturaEncabezado()
        {
            this.EPK_HistoricoFacturaDetalle = new HashSet<EPK_HistoricoFacturaDetalle>();
            this.EPK_HistoricoFacturaPago = new HashSet<EPK_HistoricoFacturaPago>();
            this.EPK_HistoricoNotaCreditoEncabezado = new HashSet<EPK_HistoricoNotaCreditoEncabezado>();
        }
    
        public int IdHistoricoFactura { get; set; }
        public string TicketFiscal { get; set; }
        public int IdCaja { get; set; }
        public string COO { get; set; }
        public string SerialMF { get; set; }
        public short IdEstatus { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public decimal PorcDescuento { get; set; }
        public int IdCliente { get; set; }
        public decimal MontoTotal { get; set; }
        public decimal MontoIVA { get; set; }
        public string NroReporteZ { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int IdUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
        public byte[] TStamp { get; set; }
        public Nullable<byte> IdTipoDocumento { get; set; }
        public string NumeroDocumento { get; set; }
    
        public virtual EPK_Caja EPK_Caja { get; set; }
        public virtual EPK_Cliente EPK_Cliente { get; set; }
        public virtual ICollection<EPK_HistoricoFacturaDetalle> EPK_HistoricoFacturaDetalle { get; set; }
        public virtual EPK_Usuario EPK_Usuario { get; set; }
        public virtual EPK_Usuario EPK_Usuario1 { get; set; }
        public virtual ICollection<EPK_HistoricoFacturaPago> EPK_HistoricoFacturaPago { get; set; }
        public virtual ICollection<EPK_HistoricoNotaCreditoEncabezado> EPK_HistoricoNotaCreditoEncabezado { get; set; }
    }
}
