//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_EfectivoRemanenteEncabezado
    {
        public EPK_EfectivoRemanenteEncabezado()
        {
            this.EPK_EfectivoRemanenteDetalle = new HashSet<EPK_EfectivoRemanenteDetalle>();
        }
    
        public int IdEfectivoR { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public int IdUsuario { get; set; }
        public decimal MontoTotal { get; set; }
        public byte[] tStamp { get; set; }
    
        public virtual ICollection<EPK_EfectivoRemanenteDetalle> EPK_EfectivoRemanenteDetalle { get; set; }
    }
}
