//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_UsuarioTienda
    {
        public int IdUsuario { get; set; }
        public int IdTienda { get; set; }
        public int IdCargo { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual EPK_Tienda EPK_Tienda { get; set; }
    }
}
