//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_ClienteFormaPago
    {
        public int IdClienteFPago { get; set; }
        public int IdCliente { get; set; }
        public byte IdFormaPago { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public bool Principal { get; set; }
        public byte[] tStamp { get; set; }
        public Nullable<byte> IdTipoDocumento { get; set; }
        public string NumeroDocumento { get; set; }
    
        public virtual EPK_Cliente EPK_Cliente { get; set; }
        public virtual EPK_FormaPago EPK_FormaPago { get; set; }
    }
}
