//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_Empleados
    {
        public EPK_Empleados()
        {
            this.EPK_EmpleadoAcceso = new HashSet<EPK_EmpleadoAcceso>();
            this.EPK_EmpleadoLocalidad = new HashSet<EPK_EmpleadoLocalidad>();
            this.EPK_FacturaEncabezado = new HashSet<EPK_FacturaEncabezado>();
            this.EPK_HuellaEmpleado = new HashSet<EPK_HuellaEmpleado>();
            this.EPK_Lecturas = new HashSet<EPK_Lecturas>();
        }
    
        public long IdEmpleado { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<System.DateTime> FechaFinRelacion { get; set; }
        public Nullable<bool> RecibeNotificacion { get; set; }
        public Nullable<System.DateTime> FechaEliminacion { get; set; }
        public string CodigoTarjeta { get; set; }
        public string Clave { get; set; }
        public Nullable<short> IdPrivilegio { get; set; }
        public Nullable<int> IdRegion { get; set; }
        public Nullable<int> IdZonaActual { get; set; }
        public Nullable<int> IdDepartamento { get; set; }
        public Nullable<int> IdCargo { get; set; }
        public byte[] TStamp { get; set; }
        public Nullable<short> IdModoVerificacion { get; set; }
        public Nullable<System.DateTime> FechaEgreso { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
    
        public virtual ICollection<EPK_EmpleadoAcceso> EPK_EmpleadoAcceso { get; set; }
        public virtual ICollection<EPK_EmpleadoLocalidad> EPK_EmpleadoLocalidad { get; set; }
        public virtual EPK_ModoVerificacion EPK_ModoVerificacion { get; set; }
        public virtual EPK_Privilegio EPK_Privilegio { get; set; }
        public virtual EPK_Usuario EPK_Usuario { get; set; }
        public virtual ICollection<EPK_FacturaEncabezado> EPK_FacturaEncabezado { get; set; }
        public virtual ICollection<EPK_HuellaEmpleado> EPK_HuellaEmpleado { get; set; }
        public virtual ICollection<EPK_Lecturas> EPK_Lecturas { get; set; }
    }
}
