//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_Funcionalidad
    {
        public int IdFuncionalidad { get; set; }
        public int IdGrupoFuncionalidad { get; set; }
        public int IdTipoFuncionalidad { get; set; }
        public string Descripcion { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual EPK_GrupoFuncionalidad EPK_GrupoFuncionalidad { get; set; }
        public virtual EPK_TipoFuncionalidad EPK_TipoFuncionalidad { get; set; }
    }
}
