//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_Tienda_old
    {
        public EPK_Tienda_old()
        {
            this.EPK_Empleado = new HashSet<EPK_Empleado>();
        }
    
        public string CodTienda { get; set; }
        public int IdOrganizacion { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Sabado { get; set; }
        public Nullable<bool> Domingo { get; set; }
        public Nullable<bool> Outlet { get; set; }
        public Nullable<short> IdCiudad { get; set; }
        public Nullable<short> IdEstado { get; set; }
        public Nullable<bool> Activa { get; set; }
        public Nullable<bool> PagaComisiones { get; set; }
        public string CodigoDynamics { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual ICollection<EPK_Empleado> EPK_Empleado { get; set; }
        public virtual EPK_Organizacion EPK_Organizacion { get; set; }
    }
}
