//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_MaquinaFiscal
    {
        public long IdOrganizacion { get; set; }
        public string CodTienda { get; set; }
        public string CodMaquina { get; set; }
        public bool Operativa { get; set; }
        public Nullable<System.DateTime> FechaFinOperacion { get; set; }
        public Nullable<System.DateTime> FechaInicioOperacion { get; set; }
        public byte[] TStamp { get; set; }
    }
}
