//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_Cargo
    {
        public int IdCargo { get; set; }
        public string CodCargo { get; set; }
        public string NombreCargo { get; set; }
        public Nullable<byte> IdNivel { get; set; }
        public Nullable<bool> ComisionTotal { get; set; }
        public Nullable<decimal> PorcentajeComision { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string CargoComision { get; set; }
        public byte[] TStamp { get; set; }
    }
}
