//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_FormaPago
    {
        public EPK_FormaPago()
        {
            this.EPK_CierreCajeroPagos = new HashSet<EPK_CierreCajeroPagos>();
            this.EPK_CierreCajeroPOS = new HashSet<EPK_CierreCajeroPOS>();
            this.EPK_CierreVentaPagos = new HashSet<EPK_CierreVentaPagos>();
            this.EPK_CierreVentaPOS = new HashSet<EPK_CierreVentaPOS>();
            this.EPK_ClienteFormaPago = new HashSet<EPK_ClienteFormaPago>();
            this.EPK_FacturaPago = new HashSet<EPK_FacturaPago>();
            this.EPK_HistoricoFacturaPago = new HashSet<EPK_HistoricoFacturaPago>();
            this.EPK_TipoTiendaFormaPago = new HashSet<EPK_TipoTiendaFormaPago>();
        }
    
        public byte IdFormaPago { get; set; }
        public string Codigo_Pago { get; set; }
        public string Descripcion { get; set; }
        public byte[] Logo { get; set; }
        public string MimeType { get; set; }
        public string FileName { get; set; }
        public bool Activa { get; set; }
        public bool RequiereAutorizacion { get; set; }
        public byte[] TStamp { get; set; }
        public bool DatosBanco { get; set; }
        public bool DatosPOS { get; set; }
        public bool Restringida { get; set; }
        public Nullable<short> Maximo { get; set; }
    
        public virtual ICollection<EPK_CierreCajeroPagos> EPK_CierreCajeroPagos { get; set; }
        public virtual ICollection<EPK_CierreCajeroPOS> EPK_CierreCajeroPOS { get; set; }
        public virtual ICollection<EPK_CierreVentaPagos> EPK_CierreVentaPagos { get; set; }
        public virtual ICollection<EPK_CierreVentaPOS> EPK_CierreVentaPOS { get; set; }
        public virtual ICollection<EPK_ClienteFormaPago> EPK_ClienteFormaPago { get; set; }
        public virtual ICollection<EPK_FacturaPago> EPK_FacturaPago { get; set; }
        public virtual ICollection<EPK_HistoricoFacturaPago> EPK_HistoricoFacturaPago { get; set; }
        public virtual ICollection<EPK_TipoTiendaFormaPago> EPK_TipoTiendaFormaPago { get; set; }
    }
}
