//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_CierreCajeroPOS
    {
        public long IdCierre { get; set; }
        public int IdTienda { get; set; }
        public byte IdFormaPago { get; set; }
        public int IdPOS { get; set; }
        public short LotePOS { get; set; }
        public decimal MontoPOS { get; set; }
        public decimal MontoPago { get; set; }
        public string Observacion { get; set; }
        public byte[] tStamp { get; set; }
    
        public virtual EPK_CierreCajeroEncabezado EPK_CierreCajeroEncabezado { get; set; }
        public virtual EPK_FormaPago EPK_FormaPago { get; set; }
        public virtual EPK_POS EPK_POS { get; set; }
        public virtual EPK_Tienda EPK_Tienda { get; set; }
    }
}
