//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_POSTienda
    {
        public int IdPOS { get; set; }
        public int IdTienda { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string SerialPOS { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual EPK_POS EPK_POS { get; set; }
        public virtual EPK_Tienda EPK_Tienda { get; set; }
    }
}
