//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_EmpleadoAcceso
    {
        public int IdRegion { get; set; }
        public long IdEmpleado { get; set; }
        public short IdGrupo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaEliminacion { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual EPK_Empleados EPK_Empleados { get; set; }
        public virtual EPK_Region EPK_Region { get; set; }
    }
}
