//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_Insumos
    {
        public int IdInsumo { get; set; }
        public string Nombre { get; set; }
        public Nullable<short> IdTipoInsumo { get; set; }
        public byte[] Foto { get; set; }
        public string Nota { get; set; }
        public Nullable<short> Existencia { get; set; }
        public Nullable<short> Entradas { get; set; }
        public Nullable<short> Salidas { get; set; }
        public Nullable<bool> Habilitado { get; set; }
    
        public virtual EPK_TipoInsumo EPK_TipoInsumo { get; set; }
    }
}
