//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_ActualizacionEncabezado
    {
        public EPK_ActualizacionEncabezado()
        {
            this.EPK_ActualizacionArticulo = new HashSet<EPK_ActualizacionArticulo>();
            this.EPK_LogActualizacion = new HashSet<EPK_LogActualizacion>();
            this.EPK_ActualizacionColeccion = new HashSet<EPK_ActualizacionColeccion>();
        }
    
        public int IdActualizacion { get; set; }
        public string Descripcion { get; set; }
        public short TipoActualizacion { get; set; }
        public Nullable<short> IdEstatus { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.DateTime> FechaRecepcion { get; set; }
        public Nullable<System.DateTime> FechaProcesamiento { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<int> CantidadDetalles { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual ICollection<EPK_ActualizacionArticulo> EPK_ActualizacionArticulo { get; set; }
        public virtual ICollection<EPK_LogActualizacion> EPK_LogActualizacion { get; set; }
        public virtual ICollection<EPK_ActualizacionColeccion> EPK_ActualizacionColeccion { get; set; }
    }
}
