//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_Articulo
    {
        public EPK_Articulo()
        {
            this.EPK_ActualizacionArticulo = new HashSet<EPK_ActualizacionArticulo>();
            this.EPK_ClienteCompra = new HashSet<EPK_ClienteCompra>();
            this.EPK_FacturaDetalle = new HashSet<EPK_FacturaDetalle>();
            this.EPK_FacturaEsperaDetalle = new HashSet<EPK_FacturaEsperaDetalle>();
            this.EPK_HistoricoFacturaDetalle = new HashSet<EPK_HistoricoFacturaDetalle>();
            this.EPK_HistoricoNotaCreditoDetalle = new HashSet<EPK_HistoricoNotaCreditoDetalle>();
            this.EPK_NotaCreditoDetalle = new HashSet<EPK_NotaCreditoDetalle>();
            this.EPK_NotaCreditoEsperaDetalle = new HashSet<EPK_NotaCreditoEsperaDetalle>();
        }
    
        public int IdArticulo { get; set; }
        public string CodigoArticulo { get; set; }
        public int IdReferencia { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdColor { get; set; }
        public Nullable<int> IdTalla { get; set; }
        public Nullable<decimal> PrecioGravableInicial { get; set; }
        public decimal PrecioGravable { get; set; }
        public Nullable<decimal> PrecioExentoInicial { get; set; }
        public decimal PrecioExento { get; set; }
        public short Existencia { get; set; }
        public Nullable<int> ExistenciaAlmacen { get; set; }
        public bool Activo { get; set; }
        public bool Exento { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] TStamp { get; set; }
        public Nullable<System.DateTime> FechaInicioBloqueo { get; set; }
        public Nullable<System.DateTime> FechaFinBloqueo { get; set; }
    
        public virtual ICollection<EPK_ActualizacionArticulo> EPK_ActualizacionArticulo { get; set; }
        public virtual EPK_Color EPK_Color { get; set; }
        public virtual EPK_Referencia EPK_Referencia { get; set; }
        public virtual EPK_Talla EPK_Talla { get; set; }
        public virtual ICollection<EPK_ClienteCompra> EPK_ClienteCompra { get; set; }
        public virtual ICollection<EPK_FacturaDetalle> EPK_FacturaDetalle { get; set; }
        public virtual ICollection<EPK_FacturaEsperaDetalle> EPK_FacturaEsperaDetalle { get; set; }
        public virtual ICollection<EPK_HistoricoFacturaDetalle> EPK_HistoricoFacturaDetalle { get; set; }
        public virtual ICollection<EPK_HistoricoNotaCreditoDetalle> EPK_HistoricoNotaCreditoDetalle { get; set; }
        public virtual ICollection<EPK_NotaCreditoDetalle> EPK_NotaCreditoDetalle { get; set; }
        public virtual ICollection<EPK_NotaCreditoEsperaDetalle> EPK_NotaCreditoEsperaDetalle { get; set; }
    }
}
