//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_Feriados
    {
        public EPK_Feriados()
        {
            this.EPK_FeriadosRegion = new HashSet<EPK_FeriadosRegion>();
        }
    
        public short IdFeriado { get; set; }
        public string Descripcion { get; set; }
        public int IdOrganizacion { get; set; }
        public bool Anual { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual ICollection<EPK_FeriadosRegion> EPK_FeriadosRegion { get; set; }
        public virtual EPK_Organizacion EPK_Organizacion { get; set; }
    }
}
