//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_Pais
    {
        public EPK_Pais()
        {
            this.EPK_Organizacion = new HashSet<EPK_Organizacion>();
            this.EPK_Region = new HashSet<EPK_Region>();
            this.EPK_RegionPais = new HashSet<EPK_RegionPais>();
        }
    
        public int IdPais { get; set; }
        public string Nombre { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual ICollection<EPK_Organizacion> EPK_Organizacion { get; set; }
        public virtual ICollection<EPK_Region> EPK_Region { get; set; }
        public virtual ICollection<EPK_RegionPais> EPK_RegionPais { get; set; }
    }
}
