//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_EfectivoRemanenteDetalle
    {
        public int IdEfectivoR { get; set; }
        public byte IdDenominacion { get; set; }
        public int CantidadAlivio { get; set; }
        public int CantidadDeposito { get; set; }
        public int CantidadRemanente { get; set; }
        public int CantidadActual { get; set; }
        public byte[] tStamp { get; set; }
    
        public virtual EPK_Denominacion EPK_Denominacion { get; set; }
        public virtual EPK_EfectivoRemanenteEncabezado EPK_EfectivoRemanenteEncabezado { get; set; }
    }
}
