//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_HistoricoNotaCreditoEncabezado
    {
        public EPK_HistoricoNotaCreditoEncabezado()
        {
            this.EPK_HistoricoNotaCreditoDetalle = new HashSet<EPK_HistoricoNotaCreditoDetalle>();
        }
    
        public int IdNota { get; set; }
        public int IdFactura { get; set; }
        public short IdEstatus { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public decimal MontoTotal { get; set; }
        public string TicketFiscal { get; set; }
        public string Motivo { get; set; }
        public string Observacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int IdUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual EPK_HistoricoFacturaEncabezado EPK_HistoricoFacturaEncabezado { get; set; }
        public virtual ICollection<EPK_HistoricoNotaCreditoDetalle> EPK_HistoricoNotaCreditoDetalle { get; set; }
        public virtual EPK_Usuario EPK_Usuario { get; set; }
        public virtual EPK_Usuario EPK_Usuario1 { get; set; }
    }
}
