//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_RegionPais
    {
        public EPK_RegionPais()
        {
            this.EPK_Estado = new HashSet<EPK_Estado>();
        }
    
        public int IdRegionPais { get; set; }
        public string Nombre { get; set; }
        public int IdPais { get; set; }
        public Nullable<byte> DiaPedido { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual ICollection<EPK_Estado> EPK_Estado { get; set; }
        public virtual EPK_Pais EPK_Pais { get; set; }
    }
}
