//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_DepositoEncabezado
    {
        public EPK_DepositoEncabezado()
        {
            this.EPK_DepositoCheque = new HashSet<EPK_DepositoCheque>();
            this.EPK_DepositoDetalle = new HashSet<EPK_DepositoDetalle>();
        }
    
        public long IdDeposito { get; set; }
        public int IdTienda { get; set; }
        public System.DateTime FechaDeposito { get; set; }
        public bool DepositoValores { get; set; }
        public decimal MontoEfectivo { get; set; }
        public Nullable<decimal> MontoCheque { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public System.DateTime FechaVenta { get; set; }
        public string SerialPrecinto { get; set; }
        public string NumeroTransaccion { get; set; }
        public Nullable<int> IdEntidad { get; set; }
        public int IdUsuarioResponsable { get; set; }
        public Nullable<int> IdUsuarioResponsable2 { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> FechaRecogida { get; set; }
        public byte[] ImagenCataporte { get; set; }
        public string MimeType { get; set; }
        public string FileName { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual ICollection<EPK_DepositoCheque> EPK_DepositoCheque { get; set; }
        public virtual ICollection<EPK_DepositoDetalle> EPK_DepositoDetalle { get; set; }
        public virtual EPK_EntidadFinanciera EPK_EntidadFinanciera { get; set; }
        public virtual EPK_Tienda EPK_Tienda { get; set; }
        public virtual EPK_Usuario EPK_Usuario { get; set; }
        public virtual EPK_Usuario EPK_Usuario1 { get; set; }
    }
}
