//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_AlivioEfectivoEncabezado
    {
        public EPK_AlivioEfectivoEncabezado()
        {
            this.EPK_AlivioEfectivoDetalle = new HashSet<EPK_AlivioEfectivoDetalle>();
        }
    
        public long IdAlivioEfectivo { get; set; }
        public int IdUsuarioCajero { get; set; }
        public int IdCaja { get; set; }
        public System.DateTime FechaAlivio { get; set; }
        public System.TimeSpan HoraAlivio { get; set; }
        public decimal TotalPagosEfectivo { get; set; }
        public decimal TotalAlivio { get; set; }
        public Nullable<decimal> TotalAprobado { get; set; }
        public Nullable<byte> IdMotivoDesc { get; set; }
        public string Observacion { get; set; }
        public short IdEstatus { get; set; }
        public int IdUsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<int> IdUsuarioAprobador { get; set; }
        public Nullable<System.DateTime> FechaHoraAprobacion { get; set; }
    
        public virtual ICollection<EPK_AlivioEfectivoDetalle> EPK_AlivioEfectivoDetalle { get; set; }
        public virtual EPK_Usuario EPK_Usuario { get; set; }
        public virtual EPK_Usuario EPK_Usuario1 { get; set; }
        public virtual EPK_Usuario EPK_Usuario2 { get; set; }
        public virtual EPK_Caja EPK_Caja { get; set; }
        public virtual EPK_MotivoDescuento EPK_MotivoDescuento { get; set; }
    }
}
