//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_Estado
    {
        public EPK_Estado()
        {
            this.EPK_Ciudad = new HashSet<EPK_Ciudad>();
            this.EPK_Cliente = new HashSet<EPK_Cliente>();
        }
    
        public int IdEstado { get; set; }
        public string Nombre { get; set; }
        public int IdRegionPais { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual ICollection<EPK_Ciudad> EPK_Ciudad { get; set; }
        public virtual ICollection<EPK_Cliente> EPK_Cliente { get; set; }
        public virtual EPK_RegionPais EPK_RegionPais { get; set; }
    }
}
