//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_Color
    {
        public EPK_Color()
        {
            this.EPK_Articulo = new HashSet<EPK_Articulo>();
        }
    
        public int IdColor { get; set; }
        public string CodigoColor { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual ICollection<EPK_Articulo> EPK_Articulo { get; set; }
    }
}
