//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_ActualizacionArticulo
    {
        public int IdActualizacion { get; set; }
        public int IdArticulo { get; set; }
        public Nullable<decimal> PrecioGravable { get; set; }
        public Nullable<decimal> PrecioExento { get; set; }
        public Nullable<long> Existencia { get; set; }
        public Nullable<long> ExistenciaAlmacen { get; set; }
        public Nullable<bool> Activo { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual EPK_ActualizacionEncabezado EPK_ActualizacionEncabezado { get; set; }
        public virtual EPK_Articulo EPK_Articulo { get; set; }
    }
}
