//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_TipoDescuento
    {
        public EPK_TipoDescuento()
        {
            this.EPK_Cliente = new HashSet<EPK_Cliente>();
            this.EPK_Descuento = new HashSet<EPK_Descuento>();
        }
    
        public byte IdTipoDescuento { get; set; }
        public string Descripcion { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual ICollection<EPK_Cliente> EPK_Cliente { get; set; }
        public virtual ICollection<EPK_Descuento> EPK_Descuento { get; set; }
    }
}
