//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_UsuarioBackup
    {
        public string IdUsuario { get; set; }
        public string Identificacion { get; set; }
        public string PalabraClave { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<int> IdPreguntaSecreta { get; set; }
        public string RespuestaSecreta { get; set; }
        public Nullable<int> IdOrganizacion { get; set; }
        public string IdLenguaje { get; set; }
        public Nullable<long> IdPaginaPrincipal { get; set; }
        public Nullable<int> IdPerfil { get; set; }
        public string CodTienda { get; set; }
        public Nullable<bool> Activo { get; set; }
        public byte[] TStamp { get; set; }
    }
}
