//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_Dispositivo
    {
        public EPK_Dispositivo()
        {
            this.EPK_CajaDispositivo = new HashSet<EPK_CajaDispositivo>();
            this.EPK_CajaDispositivoHistorico = new HashSet<EPK_CajaDispositivoHistorico>();
            this.EPK_CierreMaquinaFiscal = new HashSet<EPK_CierreMaquinaFiscal>();
        }
    
        public int IdDispositivo { get; set; }
        public short IdTipoDispositivo { get; set; }
        public string Serial { get; set; }
        public System.DateTime FechaInicioOperacion { get; set; }
        public Nullable<System.DateTime> FechaFinOperacion { get; set; }
        public short IdEstatus { get; set; }
        public short IdMarca { get; set; }
        public string NroReporteZ { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual ICollection<EPK_CajaDispositivo> EPK_CajaDispositivo { get; set; }
        public virtual ICollection<EPK_CajaDispositivoHistorico> EPK_CajaDispositivoHistorico { get; set; }
        public virtual EPK_Estatus EPK_Estatus { get; set; }
        public virtual EPK_TipoDispositivo EPK_TipoDispositivo { get; set; }
        public virtual ICollection<EPK_CierreMaquinaFiscal> EPK_CierreMaquinaFiscal { get; set; }
    }
}
