//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_TipoServicios
    {
        public short IdServicio { get; set; }
        public string Descripcion { get; set; }
        public string Observacion { get; set; }
        public Nullable<bool> Habilitado { get; set; }
    }
}
