//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_Almacen
    {
        public byte IdAlmacen { get; set; }
        public string CodigoAlmacen { get; set; }
        public string Descripcion { get; set; }
        public short IdCiudad { get; set; }
        public short IdEstado { get; set; }
        public bool Activa { get; set; }
        public long IdOrganizacion { get; set; }
        public string CodigoTienda { get; set; }
        public Nullable<byte> IdAlmacenReposicion { get; set; }
        public byte[] TStamp { get; set; }
        public Nullable<byte> MinStockPieza { get; set; }
        public Nullable<byte> FrecuenciaPedido { get; set; }
        public Nullable<byte> DiaPedido { get; set; }
    }
}
