//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_Zonas
    {
        public int IdRegion { get; set; }
        public short IdZona { get; set; }
        public string Descripcion { get; set; }
        public string Intervalos { get; set; }
        public Nullable<System.TimeSpan> LunesHoraE { get; set; }
        public Nullable<System.TimeSpan> LunesHoraS { get; set; }
        public Nullable<System.TimeSpan> MartesHoraE { get; set; }
        public Nullable<System.TimeSpan> MartesHoraS { get; set; }
        public Nullable<System.TimeSpan> MiercolesHoraE { get; set; }
        public Nullable<System.TimeSpan> MiercolesHoraS { get; set; }
        public Nullable<System.TimeSpan> JuevesHoraE { get; set; }
        public Nullable<System.TimeSpan> JuevesHoraS { get; set; }
        public Nullable<System.TimeSpan> ViernesHoraE { get; set; }
        public Nullable<System.TimeSpan> ViernesHoraS { get; set; }
        public Nullable<System.TimeSpan> SabadoHoraE { get; set; }
        public Nullable<System.TimeSpan> SabadoHoraS { get; set; }
        public Nullable<System.TimeSpan> DomingoHoraE { get; set; }
        public Nullable<System.TimeSpan> DomingoHoraS { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual EPK_Region EPK_Region { get; set; }
    }
}
