//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_LogErrores
    {
        public int IdError { get; set; }
        public string Procedimiento { get; set; }
        public Nullable<int> Linea { get; set; }
        public string NroError { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaError { get; set; }
        public string Usuario { get; set; }
        public byte[] TStamp { get; set; }
    }
}
