//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_CombinacionGrupos
    {
        public int IdRegion { get; set; }
        public short IdCombinacion { get; set; }
        public string Descripcion { get; set; }
        public Nullable<short> IdGrupo1 { get; set; }
        public Nullable<short> IdGrupo2 { get; set; }
        public Nullable<short> IdGrupo3 { get; set; }
        public Nullable<short> IdGrupo4 { get; set; }
        public Nullable<short> IdGrupo5 { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual EPK_Region EPK_Region { get; set; }
    }
}
