//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_Parentesco
    {
        public long IdEmpleado { get; set; }
        public long IdParentesco { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<System.DateTime> FechaDeNacimiento { get; set; }
        public string Sexo { get; set; }
        public Nullable<short> IdTipoParentesco { get; set; }
        public byte[] TStamp { get; set; }
    }
}
