//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_TipoTiendaFormaPago
    {
        public short IdTipoTienda { get; set; }
        public byte IdFormaPago { get; set; }
        public bool Activa { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual EPK_FormaPago EPK_FormaPago { get; set; }
        public virtual EPK_TipoTienda EPK_TipoTienda { get; set; }
    }
}
