//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_MotivoDevolucion
    {
        public EPK_MotivoDevolucion()
        {
            this.EPK_FacturaDetalle = new HashSet<EPK_FacturaDetalle>();
        }
    
        public byte IdMotivo { get; set; }
        public string Motivo { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual ICollection<EPK_FacturaDetalle> EPK_FacturaDetalle { get; set; }
    }
}
