//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_Coleccion
    {
        public EPK_Coleccion()
        {
            this.EPK_Referencia = new HashSet<EPK_Referencia>();
            this.EPK_ActualizacionColeccion = new HashSet<EPK_ActualizacionColeccion>();
        }
    
        public int IdColeccion { get; set; }
        public string CodigoColeccion { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public bool Activo { get; set; }
        public bool Actual { get; set; }
        public Nullable<int> IdColeccionAnterior { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual ICollection<EPK_Referencia> EPK_Referencia { get; set; }
        public virtual ICollection<EPK_ActualizacionColeccion> EPK_ActualizacionColeccion { get; set; }
    }
}
