//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_App
    {
        public EPK_App()
        {
            this.EPK_Modulo = new HashSet<EPK_Modulo>();
            this.EPK_SeguridadPlantillaApp = new HashSet<EPK_SeguridadPlantillaApp>();
            this.EPK_UsuarioApp = new HashSet<EPK_UsuarioApp>();
        }
    
        public int IdApp { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string TipoAplicacion { get; set; }
        public bool Activa { get; set; }
        public byte[] Logo { get; set; }
        public string MimeType { get; set; }
        public string Filename { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual ICollection<EPK_Modulo> EPK_Modulo { get; set; }
        public virtual ICollection<EPK_SeguridadPlantillaApp> EPK_SeguridadPlantillaApp { get; set; }
        public virtual ICollection<EPK_UsuarioApp> EPK_UsuarioApp { get; set; }
    }
}
