//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_Tienda
    {
        public EPK_Tienda()
        {
            this.EPK_CierreCajeroDenominacion = new HashSet<EPK_CierreCajeroDenominacion>();
            this.EPK_CierreCajeroEncabezado = new HashSet<EPK_CierreCajeroEncabezado>();
            this.EPK_CierreCajeroPagos = new HashSet<EPK_CierreCajeroPagos>();
            this.EPK_CierreCajeroPOS = new HashSet<EPK_CierreCajeroPOS>();
            this.EPK_CierreVentaEncabezado = new HashSet<EPK_CierreVentaEncabezado>();
            this.EPK_CierreVentaPagos = new HashSet<EPK_CierreVentaPagos>();
            this.EPK_CierreVentaPOS = new HashSet<EPK_CierreVentaPOS>();
            this.EPK_DepositoCheque = new HashSet<EPK_DepositoCheque>();
            this.EPK_DepositoDetalle = new HashSet<EPK_DepositoDetalle>();
            this.EPK_FacturaDetalle = new HashSet<EPK_FacturaDetalle>();
            this.EPK_FacturaEncabezado = new HashSet<EPK_FacturaEncabezado>();
            this.EPK_FacturaPago = new HashSet<EPK_FacturaPago>();
            this.EPK_NotaCreditoDetalle = new HashSet<EPK_NotaCreditoDetalle>();
            this.EPK_NotaCreditoEncabezado = new HashSet<EPK_NotaCreditoEncabezado>();
            this.EPK_POSTienda = new HashSet<EPK_POSTienda>();
            this.EPK_TiendaTelefono = new HashSet<EPK_TiendaTelefono>();
            this.EPK_UsuarioTienda = new HashSet<EPK_UsuarioTienda>();
            this.EPK_NotaCreditoEsperaDetalle = new HashSet<EPK_NotaCreditoEsperaDetalle>();
            this.EPK_DepositoEncabezado = new HashSet<EPK_DepositoEncabezado>();
        }
    
        public int IdTienda { get; set; }
        public int IdOrganizacion { get; set; }
        public int IdCiudad { get; set; }
        public short IdTipoTienda { get; set; }
        public string CodigoTienda { get; set; }
        public string CodigoSitio { get; set; }
        public string Descripcion { get; set; }
        public string DireccionIP { get; set; }
        public string Puerto { get; set; }
        public string PiedeFactura { get; set; }
        public Nullable<int> CapacidadPiezas { get; set; }
        public Nullable<int> CapacidadPisoVta { get; set; }
        public Nullable<int> CapacidadDeposito { get; set; }
        public Nullable<int> CapacidadMezzanina { get; set; }
        public Nullable<short> EspacioPisoVta { get; set; }
        public Nullable<short> EspacioDeposito { get; set; }
        public Nullable<short> EspacioMezzanina { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public bool Activa { get; set; }
        public Nullable<byte> SitioColeccionActual { get; set; }
        public Nullable<byte> SitioColeccionesPasadas { get; set; }
        public byte[] TStamp { get; set; }
        public decimal TopeApertura { get; set; }
        public bool ClientesCentralizados { get; set; }
    
        public virtual ICollection<EPK_CierreCajeroDenominacion> EPK_CierreCajeroDenominacion { get; set; }
        public virtual ICollection<EPK_CierreCajeroEncabezado> EPK_CierreCajeroEncabezado { get; set; }
        public virtual ICollection<EPK_CierreCajeroPagos> EPK_CierreCajeroPagos { get; set; }
        public virtual ICollection<EPK_CierreCajeroPOS> EPK_CierreCajeroPOS { get; set; }
        public virtual ICollection<EPK_CierreVentaEncabezado> EPK_CierreVentaEncabezado { get; set; }
        public virtual ICollection<EPK_CierreVentaPagos> EPK_CierreVentaPagos { get; set; }
        public virtual ICollection<EPK_CierreVentaPOS> EPK_CierreVentaPOS { get; set; }
        public virtual EPK_Ciudad EPK_Ciudad { get; set; }
        public virtual ICollection<EPK_DepositoCheque> EPK_DepositoCheque { get; set; }
        public virtual ICollection<EPK_DepositoDetalle> EPK_DepositoDetalle { get; set; }
        public virtual ICollection<EPK_FacturaDetalle> EPK_FacturaDetalle { get; set; }
        public virtual ICollection<EPK_FacturaEncabezado> EPK_FacturaEncabezado { get; set; }
        public virtual ICollection<EPK_FacturaPago> EPK_FacturaPago { get; set; }
        public virtual ICollection<EPK_NotaCreditoDetalle> EPK_NotaCreditoDetalle { get; set; }
        public virtual ICollection<EPK_NotaCreditoEncabezado> EPK_NotaCreditoEncabezado { get; set; }
        public virtual EPK_Organizacion EPK_Organizacion { get; set; }
        public virtual ICollection<EPK_POSTienda> EPK_POSTienda { get; set; }
        public virtual EPK_TipoTienda EPK_TipoTienda { get; set; }
        public virtual ICollection<EPK_TiendaTelefono> EPK_TiendaTelefono { get; set; }
        public virtual ICollection<EPK_UsuarioTienda> EPK_UsuarioTienda { get; set; }
        public virtual ICollection<EPK_NotaCreditoEsperaDetalle> EPK_NotaCreditoEsperaDetalle { get; set; }
        public virtual ICollection<EPK_DepositoEncabezado> EPK_DepositoEncabezado { get; set; }
    }
}
