//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_Ciudad
    {
        public EPK_Ciudad()
        {
            this.EPK_Tienda = new HashSet<EPK_Tienda>();
        }
    
        public int IdCiudad { get; set; }
        public string Nombre { get; set; }
        public int IdEstado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual EPK_Estado EPK_Estado { get; set; }
        public virtual ICollection<EPK_Tienda> EPK_Tienda { get; set; }
    }
}
