//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_Temporada
    {
        public EPK_Temporada()
        {
            this.EPK_TemporadaGrupo = new HashSet<EPK_TemporadaGrupo>();
        }
    
        public int IdTemporada { get; set; }
        public int Anno { get; set; }
        public byte Semana { get; set; }
        public decimal PorcentajeAumento { get; set; }
        public byte SemanasAnalisis { get; set; }
        public byte IdTipoTemporada { get; set; }
        public bool MaximoStock { get; set; }
        public byte SemanasAnticipacion { get; set; }
    
        public virtual EPK_TipoTemporada EPK_TipoTemporada { get; set; }
        public virtual ICollection<EPK_TemporadaGrupo> EPK_TemporadaGrupo { get; set; }
    }
}
