//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_POS
    {
        public EPK_POS()
        {
            this.EPK_CierreCajeroPOS = new HashSet<EPK_CierreCajeroPOS>();
            this.EPK_CierreVentaPOS = new HashSet<EPK_CierreVentaPOS>();
            this.EPK_FacturaPago = new HashSet<EPK_FacturaPago>();
            this.EPK_HistoricoFacturaPago = new HashSet<EPK_HistoricoFacturaPago>();
            this.EPK_POSTienda = new HashSet<EPK_POSTienda>();
        }
    
        public int IdPOS { get; set; }
        public string Descripcion { get; set; }
        public int IdEntidad { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual ICollection<EPK_CierreCajeroPOS> EPK_CierreCajeroPOS { get; set; }
        public virtual ICollection<EPK_CierreVentaPOS> EPK_CierreVentaPOS { get; set; }
        public virtual EPK_EntidadFinanciera EPK_EntidadFinanciera { get; set; }
        public virtual ICollection<EPK_FacturaPago> EPK_FacturaPago { get; set; }
        public virtual ICollection<EPK_HistoricoFacturaPago> EPK_HistoricoFacturaPago { get; set; }
        public virtual ICollection<EPK_POSTienda> EPK_POSTienda { get; set; }
    }
}
