//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_Objeto
    {
        public EPK_Objeto()
        {
            this.EPK_ObjetoAccion = new HashSet<EPK_ObjetoAccion>();
            this.EPK_ObjetoEstatus = new HashSet<EPK_ObjetoEstatus>();
            this.EPK_PerfilObjetos = new HashSet<EPK_PerfilObjetos>();
        }
    
        public int IdObjeto { get; set; }
        public string Descripcion { get; set; }
        public int IdModulo { get; set; }
        public string NombreTecnico { get; set; }
        public string NombreFuncional { get; set; }
        public Nullable<int> IdPadre { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual EPK_Modulo EPK_Modulo { get; set; }
        public virtual ICollection<EPK_ObjetoAccion> EPK_ObjetoAccion { get; set; }
        public virtual ICollection<EPK_ObjetoEstatus> EPK_ObjetoEstatus { get; set; }
        public virtual ICollection<EPK_PerfilObjetos> EPK_PerfilObjetos { get; set; }
    }
}
