//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_Mensaje
    {
        public EPK_Mensaje()
        {
            this.EPK_MensajeTerminal = new HashSet<EPK_MensajeTerminal>();
        }
    
        public int IdMensaje { get; set; }
        public Nullable<short> Bandera { get; set; }
        public Nullable<short> Minutos { get; set; }
        public string FechaInicio { get; set; }
        public string Mensaje { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual ICollection<EPK_MensajeTerminal> EPK_MensajeTerminal { get; set; }
    }
}
