//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_TipoInsumo
    {
        public EPK_TipoInsumo()
        {
            this.EPK_Insumos = new HashSet<EPK_Insumos>();
        }
    
        public short IdTipoInsumo { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<EPK_Insumos> EPK_Insumos { get; set; }
    }
}
