//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_Organizacion
    {
        public EPK_Organizacion()
        {
            this.EPK_Feriados = new HashSet<EPK_Feriados>();
            this.EPK_Tienda = new HashSet<EPK_Tienda>();
        }
    
        public int IdOrganizacion { get; set; }
        public string Descripcion { get; set; }
        public int IdPais { get; set; }
        public string RIF { get; set; }
        public byte[] Logo { get; set; }
        public string MimeType { get; set; }
        public string FileName { get; set; }
        public string Url { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string Email3 { get; set; }
        public string IdLenguaje { get; set; }
        public byte[] TStamp { get; set; }
        public byte[] ImagenDefault { get; set; }
        public string MimeTypeDefault { get; set; }
        public string FileNameDefault { get; set; }
    
        public virtual ICollection<EPK_Feriados> EPK_Feriados { get; set; }
        public virtual EPK_Lenguaje EPK_Lenguaje { get; set; }
        public virtual EPK_Pais EPK_Pais { get; set; }
        public virtual ICollection<EPK_Tienda> EPK_Tienda { get; set; }
    }
}
