//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_CierreVentaEncabezado
    {
        public EPK_CierreVentaEncabezado()
        {
            this.EPK_CierreVentaPagos = new HashSet<EPK_CierreVentaPagos>();
            this.EPK_CierreVentaPOS = new HashSet<EPK_CierreVentaPOS>();
        }
    
        public int IdCierreV { get; set; }
        public int IdTienda { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public int IdUsuario { get; set; }
        public string Observaciones { get; set; }
        public Nullable<decimal> MontoBase { get; set; }
        public Nullable<decimal> MontoIVA { get; set; }
        public Nullable<decimal> MontoDescuento { get; set; }
        public Nullable<decimal> MontoExento { get; set; }
        public Nullable<decimal> MontoTotal { get; set; }
        public Nullable<decimal> TotalAlivios { get; set; }
        public Nullable<decimal> TotalAperturas { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual EPK_Tienda EPK_Tienda { get; set; }
        public virtual EPK_Usuario EPK_Usuario { get; set; }
        public virtual ICollection<EPK_CierreVentaPagos> EPK_CierreVentaPagos { get; set; }
        public virtual ICollection<EPK_CierreVentaPOS> EPK_CierreVentaPOS { get; set; }
    }
}
