//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_MensajeTerminal
    {
        public int IdTerminal { get; set; }
        public int IdMensaje { get; set; }
        public int IdRegion { get; set; }
        public int IdLocalidad { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaEliminacion { get; set; }
        public Nullable<long> IdUsuario { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual EPK_Mensaje EPK_Mensaje { get; set; }
    }
}
