//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_NotaCreditoEsperaEncabezado
    {
        public EPK_NotaCreditoEsperaEncabezado()
        {
            this.EPK_NotaCreditoEsperaDetalle = new HashSet<EPK_NotaCreditoEsperaDetalle>();
        }
    
        public int IdNotaCreditoE { get; set; }
        public int IdTienda { get; set; }
        public bool OrigenTienda { get; set; }
        public int IdFactura { get; set; }
        public Nullable<int> IdFacturaSust { get; set; }
        public short IdEstatus { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public decimal PorcDescuento { get; set; }
        public Nullable<decimal> MontoBase { get; set; }
        public Nullable<decimal> MontoDescuento { get; set; }
        public decimal MontoIVA { get; set; }
        public decimal MontoTotal { get; set; }
        public Nullable<int> IdNCTienda { get; set; }
        public string TicketFiscalTienda { get; set; }
        public string COO { get; set; }
        public string SerialMF { get; set; }
        public string Motivo { get; set; }
        public string Observacion { get; set; }
        public string NroReporteZ { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int IdUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
        public byte[] Imagen { get; set; }
        public string MimeType { get; set; }
        public string FileName { get; set; }
        public string NombreCliente { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual EPK_FacturaEncabezado EPK_FacturaEncabezado { get; set; }
        public virtual EPK_FacturaEncabezado EPK_FacturaEncabezado1 { get; set; }
        public virtual EPK_NotaCreditoEncabezado EPK_NotaCreditoEncabezado { get; set; }
        public virtual ICollection<EPK_NotaCreditoEsperaDetalle> EPK_NotaCreditoEsperaDetalle { get; set; }
    }
}
