//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_HistoricoArticuloExistencia
    {
        public int IdHistoricoE { get; set; }
        public string CodigoSitio { get; set; }
        public string CodigoColeccion { get; set; }
        public string CodigoGrupo { get; set; }
        public string CodigoTalla { get; set; }
        public byte Semana { get; set; }
        public short Anno { get; set; }
        public Nullable<int> Existencia { get; set; }
        public Nullable<int> Transferencia { get; set; }
        public int Venta { get; set; }
    }
}
