//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_Usuario
    {
        public EPK_Usuario()
        {
            this.EPK_AlivioEfectivoEncabezado = new HashSet<EPK_AlivioEfectivoEncabezado>();
            this.EPK_AlivioEfectivoEncabezado1 = new HashSet<EPK_AlivioEfectivoEncabezado>();
            this.EPK_AlivioEfectivoEncabezado2 = new HashSet<EPK_AlivioEfectivoEncabezado>();
            this.EPK_AperturaCajeroEncabezado = new HashSet<EPK_AperturaCajeroEncabezado>();
            this.EPK_CierreCajeroEncabezado = new HashSet<EPK_CierreCajeroEncabezado>();
            this.EPK_CierreVentaEncabezado = new HashSet<EPK_CierreVentaEncabezado>();
            this.EPK_Empleados = new HashSet<EPK_Empleados>();
            this.EPK_FacturaEncabezado = new HashSet<EPK_FacturaEncabezado>();
            this.EPK_FacturaEncabezado1 = new HashSet<EPK_FacturaEncabezado>();
            this.EPK_FacturaEsperaEncabezado = new HashSet<EPK_FacturaEsperaEncabezado>();
            this.EPK_FacturaEsperaEncabezado1 = new HashSet<EPK_FacturaEsperaEncabezado>();
            this.EPK_HistoricoFacturaEncabezado = new HashSet<EPK_HistoricoFacturaEncabezado>();
            this.EPK_HistoricoFacturaEncabezado1 = new HashSet<EPK_HistoricoFacturaEncabezado>();
            this.EPK_HistoricoNotaCreditoEncabezado = new HashSet<EPK_HistoricoNotaCreditoEncabezado>();
            this.EPK_HistoricoNotaCreditoEncabezado1 = new HashSet<EPK_HistoricoNotaCreditoEncabezado>();
            this.EPK_LogActualizacion = new HashSet<EPK_LogActualizacion>();
            this.EPK_UsuarioApp = new HashSet<EPK_UsuarioApp>();
            this.EPK_FlujoEfectivo = new HashSet<EPK_FlujoEfectivo>();
            this.EPK_DepositoEncabezado = new HashSet<EPK_DepositoEncabezado>();
            this.EPK_DepositoEncabezado1 = new HashSet<EPK_DepositoEncabezado>();
            this.EPK_VentasVolumen = new HashSet<EPK_VentasVolumen>();
        }
    
        public int IdUsuario { get; set; }
        public string Identificacion { get; set; }
        public string Login { get; set; }
        public string Clave { get; set; }
        public string Estatus { get; set; }
        public string Email { get; set; }
        public bool ReqPassChange { get; set; }
        public System.DateTime LastPassChange { get; set; }
        public string NewPasswordKey { get; set; }
        public Nullable<System.DateTime> NewPasswordReq { get; set; }
        public bool Locked { get; set; }
        public byte FailedLoginAttempts { get; set; }
        public Nullable<System.DateTime> LastLockedDate { get; set; }
        public string LastLockedReason { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] TStamp { get; set; }
        public Nullable<int> IdCajaActual { get; set; }
        public int IdTienda { get; set; }
    
        public virtual ICollection<EPK_AlivioEfectivoEncabezado> EPK_AlivioEfectivoEncabezado { get; set; }
        public virtual ICollection<EPK_AlivioEfectivoEncabezado> EPK_AlivioEfectivoEncabezado1 { get; set; }
        public virtual ICollection<EPK_AlivioEfectivoEncabezado> EPK_AlivioEfectivoEncabezado2 { get; set; }
        public virtual ICollection<EPK_AperturaCajeroEncabezado> EPK_AperturaCajeroEncabezado { get; set; }
        public virtual EPK_Caja EPK_Caja { get; set; }
        public virtual ICollection<EPK_CierreCajeroEncabezado> EPK_CierreCajeroEncabezado { get; set; }
        public virtual ICollection<EPK_CierreVentaEncabezado> EPK_CierreVentaEncabezado { get; set; }
        public virtual ICollection<EPK_Empleados> EPK_Empleados { get; set; }
        public virtual ICollection<EPK_FacturaEncabezado> EPK_FacturaEncabezado { get; set; }
        public virtual ICollection<EPK_FacturaEncabezado> EPK_FacturaEncabezado1 { get; set; }
        public virtual ICollection<EPK_FacturaEsperaEncabezado> EPK_FacturaEsperaEncabezado { get; set; }
        public virtual ICollection<EPK_FacturaEsperaEncabezado> EPK_FacturaEsperaEncabezado1 { get; set; }
        public virtual ICollection<EPK_HistoricoFacturaEncabezado> EPK_HistoricoFacturaEncabezado { get; set; }
        public virtual ICollection<EPK_HistoricoFacturaEncabezado> EPK_HistoricoFacturaEncabezado1 { get; set; }
        public virtual ICollection<EPK_HistoricoNotaCreditoEncabezado> EPK_HistoricoNotaCreditoEncabezado { get; set; }
        public virtual ICollection<EPK_HistoricoNotaCreditoEncabezado> EPK_HistoricoNotaCreditoEncabezado1 { get; set; }
        public virtual ICollection<EPK_LogActualizacion> EPK_LogActualizacion { get; set; }
        public virtual ICollection<EPK_UsuarioApp> EPK_UsuarioApp { get; set; }
        public virtual ICollection<EPK_FlujoEfectivo> EPK_FlujoEfectivo { get; set; }
        public virtual ICollection<EPK_DepositoEncabezado> EPK_DepositoEncabezado { get; set; }
        public virtual ICollection<EPK_DepositoEncabezado> EPK_DepositoEncabezado1 { get; set; }
        public virtual ICollection<EPK_VentasVolumen> EPK_VentasVolumen { get; set; }
    }
}
