//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_EmpleadoLocalidad
    {
        public int IdRegion { get; set; }
        public int IdLocalidad { get; set; }
        public long IdEmpleado { get; set; }
        public System.DateTime FechaHoraRegistro { get; set; }
        public Nullable<System.DateTime> FechaHoraEliminacion { get; set; }
        public Nullable<System.DateTime> FechaHoraInactivo { get; set; }
        public Nullable<System.DateTime> FechaHoraEnvio { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual EPK_Empleados EPK_Empleados { get; set; }
        public virtual EPK_Localidad EPK_Localidad { get; set; }
    }
}
