//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_Modulo
    {
        public EPK_Modulo()
        {
            this.EPK_Objeto = new HashSet<EPK_Objeto>();
        }
    
        public int IdModulo { get; set; }
        public int IdApp { get; set; }
        public string Descripcion { get; set; }
        public bool Activo { get; set; }
        public short IdPrioridad { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual EPK_App EPK_App { get; set; }
        public virtual EPK_PrioridadModulo EPK_PrioridadModulo { get; set; }
        public virtual ICollection<EPK_Objeto> EPK_Objeto { get; set; }
    }
}
