//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_CierreMaquinaFiscal
    {
        public long IdCierreMF { get; set; }
        public int IdTienda { get; set; }
        public int IdMaquina { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public string ReporteZ { get; set; }
        public string COO { get; set; }
        public string FacturaDesde { get; set; }
        public string FacturaHasta { get; set; }
        public Nullable<int> CantidadFacturas { get; set; }
        public Nullable<decimal> BaseImponibleFact { get; set; }
        public Nullable<decimal> ExentoFact { get; set; }
        public Nullable<decimal> DescuentoFact { get; set; }
        public Nullable<decimal> ImpuestoFact { get; set; }
        public decimal MontoTotalFact { get; set; }
        public string NCDesde { get; set; }
        public string NCHasta { get; set; }
        public Nullable<int> CantidadNC { get; set; }
        public Nullable<decimal> BaseImponibleNC { get; set; }
        public Nullable<decimal> ExentoNC { get; set; }
        public Nullable<decimal> DescuentoNC { get; set; }
        public Nullable<decimal> ImpuestoNC { get; set; }
        public Nullable<decimal> MontoTotalNC { get; set; }
        public string FacturaDesdeZ { get; set; }
        public string FacturaHastaZ { get; set; }
        public Nullable<int> CantidadFacturasZ { get; set; }
        public Nullable<decimal> BaseImponibleFactZ { get; set; }
        public Nullable<decimal> ExentoFactZ { get; set; }
        public Nullable<decimal> DescuentoFactZ { get; set; }
        public Nullable<decimal> ImpuestoFactZ { get; set; }
        public Nullable<decimal> TotalFactZ { get; set; }
        public Nullable<decimal> BaseImponibleNCZ { get; set; }
        public Nullable<decimal> ImpuestoNCZ { get; set; }
        public Nullable<decimal> ExentoNCZ { get; set; }
        public Nullable<decimal> TotalNCZ { get; set; }
        public Nullable<int> Zrestantes { get; set; }
        public byte[] tStamp { get; set; }
        public bool Manual { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        public virtual EPK_Dispositivo EPK_Dispositivo { get; set; }
    }
}
