//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_EntidadFinanciera
    {
        public EPK_EntidadFinanciera()
        {
            this.EPK_FacturaPago = new HashSet<EPK_FacturaPago>();
            this.EPK_HistoricoFacturaPago = new HashSet<EPK_HistoricoFacturaPago>();
            this.EPK_POS = new HashSet<EPK_POS>();
            this.EPK_DepositoEncabezado = new HashSet<EPK_DepositoEncabezado>();
        }
    
        public int IdEntidad { get; set; }
        public string CodSudeban { get; set; }
        public string Nombre { get; set; }
        public short MaximoPOS { get; set; }
        public byte[] Logo { get; set; }
        public string MimeType { get; set; }
        public string FileName { get; set; }
        public bool Activa { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int IdUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual ICollection<EPK_FacturaPago> EPK_FacturaPago { get; set; }
        public virtual ICollection<EPK_HistoricoFacturaPago> EPK_HistoricoFacturaPago { get; set; }
        public virtual ICollection<EPK_POS> EPK_POS { get; set; }
        public virtual ICollection<EPK_DepositoEncabezado> EPK_DepositoEncabezado { get; set; }
    }
}
