//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_AperturaCajeroEncabezado
    {
        public EPK_AperturaCajeroEncabezado()
        {
            this.EPK_AperturaCajeroDenominacion = new HashSet<EPK_AperturaCajeroDenominacion>();
        }
    
        public long IdApertura { get; set; }
        public int IdCaja { get; set; }
        public int IdCajero { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public Nullable<long> IdCierre { get; set; }
    
        public virtual ICollection<EPK_AperturaCajeroDenominacion> EPK_AperturaCajeroDenominacion { get; set; }
        public virtual EPK_Caja EPK_Caja { get; set; }
        public virtual EPK_Usuario EPK_Usuario { get; set; }
    }
}
