//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_SeguridadPlantilla
    {
        public EPK_SeguridadPlantilla()
        {
            this.EPK_SeguridadPlantillaApp = new HashSet<EPK_SeguridadPlantillaApp>();
        }
    
        public int IdPlantilla { get; set; }
        public string Descripcion { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual ICollection<EPK_SeguridadPlantillaApp> EPK_SeguridadPlantillaApp { get; set; }
    }
}
