//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_GrupoFuncionalidad
    {
        public EPK_GrupoFuncionalidad()
        {
            this.EPK_Funcionalidad = new HashSet<EPK_Funcionalidad>();
        }
    
        public int IdGrupoFuncionalidad { get; set; }
        public string Descripcion { get; set; }
        public string URL { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> Padre { get; set; }
        public Nullable<short> TipoServicio { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual ICollection<EPK_Funcionalidad> EPK_Funcionalidad { get; set; }
    }
}
