//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_VentasVolumen
    {
        public int IdVentasVolumen { get; set; }
        public int IdTienda { get; set; }
        public int IdFactura { get; set; }
        public int IdUsuarioAprobador { get; set; }
        public string Observacion { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual EPK_FacturaEncabezado EPK_FacturaEncabezado { get; set; }
        public virtual EPK_Usuario EPK_Usuario { get; set; }
    }
}
