//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_Caja
    {
        public EPK_Caja()
        {
            this.EPK_AlivioEfectivoEncabezado = new HashSet<EPK_AlivioEfectivoEncabezado>();
            this.EPK_AperturaCajeroEncabezado = new HashSet<EPK_AperturaCajeroEncabezado>();
            this.EPK_CajaDispositivo = new HashSet<EPK_CajaDispositivo>();
            this.EPK_CajaDispositivoHistorico = new HashSet<EPK_CajaDispositivoHistorico>();
            this.EPK_CierreCajeroEncabezado = new HashSet<EPK_CierreCajeroEncabezado>();
            this.EPK_FacturaEncabezado = new HashSet<EPK_FacturaEncabezado>();
            this.EPK_FacturaEsperaEncabezado = new HashSet<EPK_FacturaEsperaEncabezado>();
            this.EPK_HistoricoFacturaEncabezado = new HashSet<EPK_HistoricoFacturaEncabezado>();
            this.EPK_Usuario = new HashSet<EPK_Usuario>();
            this.EPK_FlujoEfectivo = new HashSet<EPK_FlujoEfectivo>();
            this.EPK_HistoricoContingencia = new HashSet<EPK_HistoricoContingencia>();
        }
    
        public int IdCaja { get; set; }
        public int IdTienda { get; set; }
        public string Descripcion { get; set; }
        public string DireccionMAC { get; set; }
        public string DireccionIP { get; set; }
        public string Puerto { get; set; }
        public bool EnDescuento { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual ICollection<EPK_AlivioEfectivoEncabezado> EPK_AlivioEfectivoEncabezado { get; set; }
        public virtual ICollection<EPK_AperturaCajeroEncabezado> EPK_AperturaCajeroEncabezado { get; set; }
        public virtual ICollection<EPK_CajaDispositivo> EPK_CajaDispositivo { get; set; }
        public virtual ICollection<EPK_CajaDispositivoHistorico> EPK_CajaDispositivoHistorico { get; set; }
        public virtual ICollection<EPK_CierreCajeroEncabezado> EPK_CierreCajeroEncabezado { get; set; }
        public virtual EPK_Contingencia EPK_Contingencia { get; set; }
        public virtual ICollection<EPK_FacturaEncabezado> EPK_FacturaEncabezado { get; set; }
        public virtual ICollection<EPK_FacturaEsperaEncabezado> EPK_FacturaEsperaEncabezado { get; set; }
        public virtual ICollection<EPK_HistoricoFacturaEncabezado> EPK_HistoricoFacturaEncabezado { get; set; }
        public virtual ICollection<EPK_Usuario> EPK_Usuario { get; set; }
        public virtual ICollection<EPK_FlujoEfectivo> EPK_FlujoEfectivo { get; set; }
        public virtual ICollection<EPK_HistoricoContingencia> EPK_HistoricoContingencia { get; set; }
    }
}
