//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_Politica
    {
        public int IdPolitica { get; set; }
        public int IdOrganizacion { get; set; }
        public short Nivel { get; set; }
        public string Descripcion { get; set; }
        public bool ImprimeMaquinaFiscal { get; set; }
        public byte[] TStamp { get; set; }
    }
}
