//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_LogUsuarioClave
    {
        public long IdLogClave { get; set; }
        public int IdUsuario { get; set; }
        public string Clave { get; set; }
        public System.DateTime FechaCambio { get; set; }
        public byte[] TStamp { get; set; }
    }
}
