//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_HistoricoFacturaPago
    {
        public int IdPago { get; set; }
        public byte IdFormaPago { get; set; }
        public int IdHistoricoFactura { get; set; }
        public Nullable<int> IdEntidad { get; set; }
        public Nullable<int> IdPOS { get; set; }
        public string NumeroPago { get; set; }
        public decimal Monto { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual EPK_EntidadFinanciera EPK_EntidadFinanciera { get; set; }
        public virtual EPK_FormaPago EPK_FormaPago { get; set; }
        public virtual EPK_HistoricoFacturaEncabezado EPK_HistoricoFacturaEncabezado { get; set; }
        public virtual EPK_POS EPK_POS { get; set; }
    }
}
