//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_Terminal
    {
        public EPK_Terminal()
        {
            this.EPK_EventoTerminal = new HashSet<EPK_EventoTerminal>();
            this.EPK_Lecturas = new HashSet<EPK_Lecturas>();
            this.EPK_TerminalGrupo = new HashSet<EPK_TerminalGrupo>();
        }
    
        public int IdRegion { get; set; }
        public int IdLocalidad { get; set; }
        public int IdTerminal { get; set; }
        public Nullable<short> IdTipoTerminal { get; set; }
        public string Descripcion { get; set; }
        public string DireccionIP { get; set; }
        public Nullable<int> Puerto { get; set; }
        public string DireccionMAC { get; set; }
        public string VersionFirmware { get; set; }
        public string NumeroDeSerial { get; set; }
        public string VersionSDK { get; set; }
        public string Plataforma { get; set; }
        public Nullable<short> CardFun { get; set; }
        public Nullable<short> Estatus { get; set; }
        public Nullable<System.DateTime> FechaHoraDispositivo { get; set; }
        public Nullable<System.DateTime> FechaHoraServidor { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<short> Modelo { get; set; }
        public Nullable<int> CapacidadUsuario { get; set; }
        public Nullable<int> CapacidadHuella { get; set; }
        public Nullable<int> CantidadLecturas { get; set; }
        public Nullable<int> CantidadClaves { get; set; }
        public Nullable<int> CantidadHuellas { get; set; }
        public Nullable<int> CantidadUsuarios { get; set; }
        public Nullable<bool> Principal { get; set; }
        public string Gateway { get; set; }
        public string Mascara { get; set; }
        public byte[] TStamp { get; set; }
        public bool AntiPassback { get; set; }
    
        public virtual ICollection<EPK_EventoTerminal> EPK_EventoTerminal { get; set; }
        public virtual ICollection<EPK_Lecturas> EPK_Lecturas { get; set; }
        public virtual ICollection<EPK_TerminalGrupo> EPK_TerminalGrupo { get; set; }
    }
}
