//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_Empleado
    {
        public long IdEmpleado { get; set; }
        public string CodigoEmpleado { get; set; }
        public string CodTienda { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Estatus { get; set; }
        public string CorreoElectronico { get; set; }
        public string Sexo { get; set; }
        public string CorreoElectronicoEmpresa { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<long> IdOrganizacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaFinRelacion { get; set; }
        public Nullable<bool> RecibeNotificacion { get; set; }
        public Nullable<System.DateTime> FechaEliminacion { get; set; }
        public string IdCargo { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public byte[] Foto { get; set; }
        public Nullable<short> IdZonaActual { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual EPK_Tienda_old EPK_Tienda_old { get; set; }
    }
}
