//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_Estatus
    {
        public EPK_Estatus()
        {
            this.EPK_Cliente = new HashSet<EPK_Cliente>();
            this.EPK_Dispositivo = new HashSet<EPK_Dispositivo>();
            this.EPK_FacturaEncabezado = new HashSet<EPK_FacturaEncabezado>();
            this.EPK_FacturaEsperaEncabezado = new HashSet<EPK_FacturaEsperaEncabezado>();
            this.EPK_ObjetoEstatus = new HashSet<EPK_ObjetoEstatus>();
        }
    
        public short IdEstatus { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual ICollection<EPK_Cliente> EPK_Cliente { get; set; }
        public virtual ICollection<EPK_Dispositivo> EPK_Dispositivo { get; set; }
        public virtual ICollection<EPK_FacturaEncabezado> EPK_FacturaEncabezado { get; set; }
        public virtual ICollection<EPK_FacturaEsperaEncabezado> EPK_FacturaEsperaEncabezado { get; set; }
        public virtual ICollection<EPK_ObjetoEstatus> EPK_ObjetoEstatus { get; set; }
    }
}
