//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_Perfil
    {
        public EPK_Perfil()
        {
            this.EPK_PerfilAccion = new HashSet<EPK_PerfilAccion>();
            this.EPK_PerfilObjetos = new HashSet<EPK_PerfilObjetos>();
            this.EPK_SeguridadPlantillaApp = new HashSet<EPK_SeguridadPlantillaApp>();
            this.EPK_UsuarioApp = new HashSet<EPK_UsuarioApp>();
        }
    
        public int IdPerfil { get; set; }
        public string Descripcion { get; set; }
        public bool Autorizador { get; set; }
        public short IdNivel { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public bool MostrarNiveles { get; set; }
        public bool Asistencia { get; set; }
        public bool BloqueoClave { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual EPK_NivelPerfil EPK_NivelPerfil { get; set; }
        public virtual ICollection<EPK_PerfilAccion> EPK_PerfilAccion { get; set; }
        public virtual ICollection<EPK_PerfilObjetos> EPK_PerfilObjetos { get; set; }
        public virtual ICollection<EPK_SeguridadPlantillaApp> EPK_SeguridadPlantillaApp { get; set; }
        public virtual ICollection<EPK_UsuarioApp> EPK_UsuarioApp { get; set; }
    }
}
