//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_FacturaEncabezado
    {
        public EPK_FacturaEncabezado()
        {
            this.EPK_FacturaDetalle = new HashSet<EPK_FacturaDetalle>();
            this.EPK_FacturaPago = new HashSet<EPK_FacturaPago>();
            this.EPK_NotaCreditoEncabezado = new HashSet<EPK_NotaCreditoEncabezado>();
            this.EPK_NotaCreditoEsperaEncabezado = new HashSet<EPK_NotaCreditoEsperaEncabezado>();
            this.EPK_NotaCreditoEsperaEncabezado1 = new HashSet<EPK_NotaCreditoEsperaEncabezado>();
            this.EPK_VentasVolumen = new HashSet<EPK_VentasVolumen>();
        }
    
        public int IdFactura { get; set; }
        public int IdTienda { get; set; }
        public string TicketFiscal { get; set; }
        public int IdCaja { get; set; }
        public string COO { get; set; }
        public string SerialMF { get; set; }
        public short IdEstatus { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public decimal PorcDescuento { get; set; }
        public int IdCliente { get; set; }
        public Nullable<decimal> MontoBase { get; set; }
        public Nullable<decimal> MontoDescuento { get; set; }
        public decimal MontoIVA { get; set; }
        public Nullable<decimal> MontoTotal { get; set; }
        public string NroReporteZ { get; set; }
        public Nullable<long> IdVendedor { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int IdUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
        public byte[] TStamp { get; set; }
        public Nullable<byte> IdTipoDocumento { get; set; }
        public string NumeroDocumento { get; set; }
    
        public virtual EPK_Caja EPK_Caja { get; set; }
        public virtual EPK_Cliente EPK_Cliente { get; set; }
        public virtual EPK_Empleados EPK_Empleados { get; set; }
        public virtual EPK_Estatus EPK_Estatus { get; set; }
        public virtual ICollection<EPK_FacturaDetalle> EPK_FacturaDetalle { get; set; }
        public virtual EPK_Tienda EPK_Tienda { get; set; }
        public virtual EPK_Usuario EPK_Usuario { get; set; }
        public virtual EPK_Usuario EPK_Usuario1 { get; set; }
        public virtual ICollection<EPK_FacturaPago> EPK_FacturaPago { get; set; }
        public virtual ICollection<EPK_NotaCreditoEncabezado> EPK_NotaCreditoEncabezado { get; set; }
        public virtual ICollection<EPK_NotaCreditoEsperaEncabezado> EPK_NotaCreditoEsperaEncabezado { get; set; }
        public virtual ICollection<EPK_NotaCreditoEsperaEncabezado> EPK_NotaCreditoEsperaEncabezado1 { get; set; }
        public virtual ICollection<EPK_VentasVolumen> EPK_VentasVolumen { get; set; }
    }
}
