//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPK_HuellaEmpleado
    {
        public long IdEmpleado { get; set; }
        public short IdFingerPrint { get; set; }
        public short IdFlag { get; set; }
        public string TemplateFinger { get; set; }
        public byte[] TStamp { get; set; }
    
        public virtual EPK_Empleados EPK_Empleados { get; set; }
    }
}
