//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGAN_POS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SEGAN_POS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap abrir {
            get {
                object obj = ResourceManager.GetObject("abrir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aceptar {
            get {
                object obj = ResourceManager.GetObject("aceptar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap advertencia {
            get {
                object obj = ResourceManager.GetObject("advertencia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap agregar {
            get {
                object obj = ResourceManager.GetObject("agregar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap agregar2 {
            get {
                object obj = ResourceManager.GetObject("agregar2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Amarillo {
            get {
                object obj = ResourceManager.GetObject("Amarillo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap attach {
            get {
                object obj = ResourceManager.GetObject("attach", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap attachpeq {
            get {
                object obj = ResourceManager.GetObject("attachpeq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BemaFI{0}.ini.
        /// </summary>
        internal static string BematechINI {
            get {
                return ResourceManager.GetString("BematechINI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RETORNO.TXT.
        /// </summary>
        internal static string BematechRetorno {
            get {
                return ResourceManager.GetString("BematechRetorno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bloquear {
            get {
                object obj = ResourceManager.GetObject("bloquear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap borrar {
            get {
                object obj = ResourceManager.GetObject("borrar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buscar {
            get {
                object obj = ResourceManager.GetObject("buscar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buscarpeq {
            get {
                object obj = ResourceManager.GetObject("buscarpeq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap calculadora {
            get {
                object obj = ResourceManager.GetObject("calculadora", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cambiarclave {
            get {
                object obj = ResourceManager.GetObject("cambiarclave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cambiarusuario {
            get {
                object obj = ResourceManager.GetObject("cambiarusuario", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cambioefectivo {
            get {
                object obj = ResourceManager.GetObject("cambioefectivo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cancelada {
            get {
                object obj = ResourceManager.GetObject("cancelada", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cancelar {
            get {
                object obj = ResourceManager.GetObject("cancelar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap carrito {
            get {
                object obj = ResourceManager.GetObject("carrito", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cerrar {
            get {
                object obj = ResourceManager.GetObject("cerrar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap check {
            get {
                object obj = ResourceManager.GetObject("check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap check32 {
            get {
                object obj = ResourceManager.GetObject("check32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap consultarcierredeventas {
            get {
                object obj = ResourceManager.GetObject("consultarcierredeventas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap consultarexistencia {
            get {
                object obj = ResourceManager.GetObject("consultarexistencia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap consultarfactura {
            get {
                object obj = ResourceManager.GetObject("consultarfactura", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap continuar {
            get {
                object obj = ResourceManager.GetObject("continuar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coronaepk {
            get {
                object obj = ResourceManager.GetObject("coronaepk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap descuento {
            get {
                object obj = ResourceManager.GetObject("descuento", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap editar {
            get {
                object obj = ResourceManager.GetObject("editar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ejecutar {
            get {
                object obj = ResourceManager.GetObject("ejecutar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eliminar {
            get {
                object obj = ResourceManager.GetObject("eliminar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eliminar_peq {
            get {
                object obj = ResourceManager.GetObject("eliminar_peq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap epklogo {
            get {
                object obj = ResourceManager.GetObject("epklogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al actualizar la configuración.
        /// </summary>
        internal static string ErrorActConfig {
            get {
                return ResourceManager.GetString("ErrorActConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al actualizar el depósito.
        /// </summary>
        internal static string ErrorActDep {
            get {
                return ResourceManager.GetString("ErrorActDep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error generando el cambio de efectivo.
        /// </summary>
        internal static string ErrorCambioEfectivo {
            get {
                return ResourceManager.GetString("ErrorCambioEfectivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al cargar los parámetros de facturación.
        /// </summary>
        internal static string ErrorCargaFacturacion {
            get {
                return ResourceManager.GetString("ErrorCargaFacturacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al cargar las Notas de Crédito.
        /// </summary>
        internal static string ErrorCargarNCs {
            get {
                return ResourceManager.GetString("ErrorCargarNCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al cargar los datos de la tienda.
        /// </summary>
        internal static string ErrorCargaTienda {
            get {
                return ResourceManager.GetString("ErrorCargaTienda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al generar el cierre de maquina fiscal.
        /// </summary>
        internal static string ErrorCierreMF {
            get {
                return ResourceManager.GetString("ErrorCierreMF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de conexion con la DB {0}.
        /// </summary>
        internal static string ErrorConexDB {
            get {
                return ResourceManager.GetString("ErrorConexDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener los datos del cierre.
        /// </summary>
        internal static string ErrorDatosCierre {
            get {
                return ResourceManager.GetString("ErrorDatosCierre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error creando el depósito.
        /// </summary>
        internal static string ErrorDeposito {
            get {
                return ResourceManager.GetString("ErrorDeposito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al crear la Solicitud de Nota de Crédito.
        /// </summary>
        internal static string ErrorGenSolNC {
            get {
                return ResourceManager.GetString("ErrorGenSolNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error generando el ingreso de efectivo.
        /// </summary>
        internal static string ErrorIngresoEfectivo {
            get {
                return ResourceManager.GetString("ErrorIngresoEfectivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe efectivo remanente o cheques por depositar.
        /// </summary>
        internal static string ErrorNadaDep {
            get {
                return ResourceManager.GetString("ErrorNadaDep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede acceder a esta función, por favor notifique a Soporte Técnico.
        /// </summary>
        internal static string ErrorSinAcceso {
            get {
                return ResourceManager.GetString("ErrorSinAcceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al iniciar el visor.
        /// </summary>
        internal static string ErrorVisor {
            get {
                return ResourceManager.GetString("ErrorVisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap espera {
            get {
                object obj = ResourceManager.GetObject("espera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap excel {
            get {
                object obj = ResourceManager.GetObject("excel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambio de efectivo registrado exitosamente.
        /// </summary>
        internal static string ExitoCambioEfectivo {
            get {
                return ResourceManager.GetString("ExitoCambioEfectivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturas exportadas exitosamente.
        /// </summary>
        internal static string ExitoExpoFacturas {
            get {
                return ResourceManager.GetString("ExitoExpoFacturas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reposición de Artículos exportada existosamente.
        /// </summary>
        internal static string ExitoExpoRepoArt {
            get {
                return ResourceManager.GetString("ExitoExpoRepoArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingreso de efectivo registrado exitosamente.
        /// </summary>
        internal static string ExitoIngresoEfectivo {
            get {
                return ResourceManager.GetString("ExitoIngresoEfectivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud de Nota de Crédito #{0} generada con éxito.
        /// </summary>
        internal static string ExitoSolNC {
            get {
                return ResourceManager.GetString("ExitoSolNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Facturas {
            get {
                object obj = ResourceManager.GetObject("Facturas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fincontingencia {
            get {
                object obj = ResourceManager.GetObject("fincontingencia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap green {
            get {
                object obj = ResourceManager.GetObject("green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gris {
            get {
                object obj = ResourceManager.GetObject("gris", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imagennodisp {
            get {
                object obj = ResourceManager.GetObject("imagennodisp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imprimiendo {
            get {
                object obj = ResourceManager.GetObject("imprimiendo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * CONTINGENCIA *.
        /// </summary>
        internal static string IndContingencia {
            get {
                return ResourceManager.GetString("IndContingencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ingresoefectivo {
            get {
                object obj = ResourceManager.GetObject("ingresoefectivo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interrupción de la generación del reporte Z autorizada por {0} ({1})..
        /// </summary>
        internal static string LogAbortarCierre {
            get {
                return ResourceManager.GetString("LogAbortarCierre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logoEPKpeq {
            get {
                object obj = ResourceManager.GetObject("logoEPKpeq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mainbackground {
            get {
                object obj = ResourceManager.GetObject("mainbackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap maincopy2 {
            get {
                object obj = ResourceManager.GetObject("maincopy2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mainname {
            get {
                object obj = ResourceManager.GetObject("mainname", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap menuefectivo {
            get {
                object obj = ResourceManager.GetObject("menuefectivo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap menureportes {
            get {
                object obj = ResourceManager.GetObject("menureportes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se requiere autorización para interrumpir la generación del reporte Z..
        /// </summary>
        internal static string MsgAbortarCierre {
            get {
                return ResourceManager.GetString("MsgAbortarCierre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha superado el monto establecido en caja, ¿ Desea realizar el alivio de efectivo en este momento ?.
        /// </summary>
        internal static string MsgAlivio {
            get {
                return ResourceManager.GetString("MsgAlivio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede realizar un alivio debido a que no tiene ventas en efectivo.
        /// </summary>
        internal static string MsgAlivioSinEfectivo {
            get {
                return ResourceManager.GetString("MsgAlivioSinEfectivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiene alivios de efectivo pendientes por aprobar. ¿Desea aprobar el cierre de cajero?.
        /// </summary>
        internal static string MsgAliviosPendCajero {
            get {
                return ResourceManager.GetString("MsgAliviosPendCajero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible realizar el cierre de ventas debido a que tiene alivios de efectivo pendientes por aprobar.
        /// </summary>
        internal static string MsgAliviosPendientes {
            get {
                return ResourceManager.GetString("MsgAliviosPendientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apertura de cajero realizada con éxito.
        /// </summary>
        internal static string MsgApeExito {
            get {
                return ResourceManager.GetString("MsgApeExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiene cantidades aprobadas en cero (0) ¿ Desea continuar ?.
        /// </summary>
        internal static string MsgAproAliCero {
            get {
                return ResourceManager.GetString("MsgAproAliCero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artículo inhabilitado para facturar, por favor contacte al personal de Soporte TIC.
        /// </summary>
        internal static string MsgArticuloInactivo {
            get {
                return ResourceManager.GetString("MsgArticuloInactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿ Desea autorizar el cierre de caja ?.
        /// </summary>
        internal static string MsgAutCierreCaja {
            get {
                return ResourceManager.GetString("MsgAutCierreCaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe diferencia entre los montos del sistema y los reportados ¿Desea autorizar el cierre de cajero?.
        /// </summary>
        internal static string MsgAutDifCierreCaj {
            get {
                return ResourceManager.GetString("MsgAutDifCierreCaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existen diferencias entre los montos del sistema y los reportados ¿Desea autorizar el Cierre de Cajero y el Cierre de Caja (Reporte Z)?.
        /// </summary>
        internal static string MsgAutDifCierreCaja_CierreMF {
            get {
                return ResourceManager.GetString("MsgAutDifCierreCaja_CierreMF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿ Autorizar la impresión de las Notas de Crédito ?.
        /// </summary>
        internal static string MsgAutNC {
            get {
                return ResourceManager.GetString("MsgAutNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea autorizar el cierre de cajero con monto 0 (cero) ?.
        /// </summary>
        internal static string MsgAutoCierreCero {
            get {
                return ResourceManager.GetString("MsgAutoCierreCero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El monto de la factura excede el límite permitido ({0}) para el descuento. ¿ Desea autorizar esta operación ?.
        /// </summary>
        internal static string MsgAutoLimiteDescuento {
            get {
                return ResourceManager.GetString("MsgAutoLimiteDescuento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿ Desea autorizar el alivio de efectivo ?.
        /// </summary>
        internal static string MsgAutorizarAlivio {
            get {
                return ResourceManager.GetString("MsgAutorizarAlivio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se requiere autorización para anular el comprobante.
        /// </summary>
        internal static string MsgAutorizarAnul {
            get {
                return ResourceManager.GetString("MsgAutorizarAnul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿ Autorizar la modificación de la cantidad de artículos ?.
        /// </summary>
        internal static string MsgAutorizarCambioCant {
            get {
                return ResourceManager.GetString("MsgAutorizarCambioCant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿ Autorizar la cancelación de la factura ?.
        /// </summary>
        internal static string MsgAutorizarCancel {
            get {
                return ResourceManager.GetString("MsgAutorizarCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contingencia activada. Se requiere autorización para continuar.
        /// </summary>
        internal static string MsgAutorizarCont {
            get {
                return ResourceManager.GetString("MsgAutorizarCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿ Desea efectura el cierre de cajero y terminar la sesión del usuario {0} ?.
        /// </summary>
        internal static string MsgAutorizarDesbloq {
            get {
                return ResourceManager.GetString("MsgAutorizarDesbloq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿ Autorizar descuento ?.
        /// </summary>
        internal static string MsgAutorizarDescuento {
            get {
                return ResourceManager.GetString("MsgAutorizarDescuento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿ Autorizar la devolución ?.
        /// </summary>
        internal static string MsgAutorizarDevolucion {
            get {
                return ResourceManager.GetString("MsgAutorizarDevolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿ Eliminar artículos ?.
        /// </summary>
        internal static string MsgAutorizarEliminacion {
            get {
                return ResourceManager.GetString("MsgAutorizarEliminacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se requiere autorización para utilizar esta forma de pago.
        /// </summary>
        internal static string MsgAutorizarFPago {
            get {
                return ResourceManager.GetString("MsgAutorizarFPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese las credenciales del personal autorizado.
        /// </summary>
        internal static string MsgAutorizarMF {
            get {
                return ResourceManager.GetString("MsgAutorizarMF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿ Autorizar selección de vendedor ?.
        /// </summary>
        internal static string MsgAutorizarSelVendedor {
            get {
                return ResourceManager.GetString("MsgAutorizarSelVendedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede realizar la apertura debido a que ya la realizó previamente.
        /// </summary>
        internal static string MsgCajaYaAbierta {
            get {
                return ResourceManager.GetString("MsgCajaYaAbierta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambio de clave efectuado.
        /// </summary>
        internal static string MsgCambioClaveExitoso {
            get {
                return ResourceManager.GetString("MsgCambioClaveExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cambio no debe exceder {0}.
        /// </summary>
        internal static string MsgCambioMax {
            get {
                return ResourceManager.GetString("MsgCambioMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuerde registrar el monto del fondo de caja.
        /// </summary>
        internal static string MsgCierreCajFondo {
            get {
                return ResourceManager.GetString("MsgCierreCajFondo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe completar los cierres pendientes antes de iniciar la facturación.
        /// </summary>
        internal static string MsgCierreCajPend {
            get {
                return ResourceManager.GetString("MsgCierreCajPend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede realizar un alivio debido a que tiene cierres pendientes.
        /// </summary>
        internal static string MsgCierreCajPendAli {
            get {
                return ResourceManager.GetString("MsgCierreCajPendAli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existen Cierres de Cajeros pendientes por efectuarse, verifique por favor.
        /// </summary>
        internal static string MsgCierresCajPend {
            get {
                return ResourceManager.GetString("MsgCierresCajPend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cierre de ventas ya fué efectuado para el día actual. No puede accesar a esta función.
        /// </summary>
        internal static string MsgCierreVentaExiste {
            get {
                return ResourceManager.GetString("MsgCierreVentaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario {0}: clave incorrecta.
        /// </summary>
        internal static string MsgClaveIncorrecta {
            get {
                return ResourceManager.GetString("MsgClaveIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código del artículo está inhabilitado, verifique por favor..
        /// </summary>
        internal static string MsgCodigoArtInac {
            get {
                return ResourceManager.GetString("MsgCodigoArtInac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró el código..
        /// </summary>
        internal static string MsgCodigoArtNoEnc {
            get {
                return ResourceManager.GetString("MsgCodigoArtNoEnc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración actualizada exitosamente.
        /// </summary>
        internal static string MsgConfAct {
            get {
                return ResourceManager.GetString("MsgConfAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El alivio reportado por el Cajero {0} es de {1:C2} y el monto aprobado por usted es de {2:C2}. ¿Está seguro que desea aprobar este alivio de efectivo?.
        /// </summary>
        internal static string MsgConfApAlivio {
            get {
                return ResourceManager.GetString("MsgConfApAlivio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que los datos ingresados son correctos?.
        /// </summary>
        internal static string MsgConfDatos {
            get {
                return ResourceManager.GetString("MsgConfDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿ Desea salir del sistema ?.
        /// </summary>
        internal static string MsgConfirmarSalir {
            get {
                return ResourceManager.GetString("MsgConfirmarSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se generará un nuevo reporte X, ¿ Desea Continuar ?.
        /// </summary>
        internal static string MsgConfirmarX {
            get {
                return ResourceManager.GetString("MsgConfirmarX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se generará el reporte Z del día, ¿ Desea Continuar ?.
        /// </summary>
        internal static string MsgConfirmarZ {
            get {
                return ResourceManager.GetString("MsgConfirmarZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se creará una nota de crédito para la factura actual. ¿ Está seguro ?.
        /// </summary>
        internal static string MsgConfirmNotaC {
            get {
                return ResourceManager.GetString("MsgConfirmNotaC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se creará una Solicitud de Nota de Crédito para la factura actual. ¿ Está seguro ?.
        /// </summary>
        internal static string MsgConfirmSolNC {
            get {
                return ResourceManager.GetString("MsgConfirmSolNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se creará una Solicitud de Nota de Crédito para la factura actual sin factura sustituta. ¿ Desea continuar ?.
        /// </summary>
        internal static string MsgConfirmSolNCNoSust {
            get {
                return ResourceManager.GetString("MsgConfirmSolNCNoSust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cupón #{0} anulado. Impresora lista para emitir nuevos tickets.
        /// </summary>
        internal static string MsgCuponAnulado {
            get {
                return ResourceManager.GetString("MsgCuponAnulado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depósito actualizado correctamente.
        /// </summary>
        internal static string MsgDepAct {
            get {
                return ResourceManager.GetString("MsgDepAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depósito creado con éxito.
        /// </summary>
        internal static string MsgDepCreado {
            get {
                return ResourceManager.GetString("MsgDepCreado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe diferencia entre los montos del sistema y los reportados ¿Desea continuar?.
        /// </summary>
        internal static string MsgDifCierreCaj {
            get {
                return ResourceManager.GetString("MsgDifCierreCaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe una diferencia entre los montos de sistema y los reportados. Por favor indique el motivo en el campo Observaciones..
        /// </summary>
        internal static string MsgDifCierreVen {
            get {
                return ResourceManager.GetString("MsgDifCierreVen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error creando el alivio de efectivo.
        /// </summary>
        internal static string MsgErrorAlivio {
            get {
                return ResourceManager.GetString("MsgErrorAlivio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario o contraseña incorrecto..
        /// </summary>
        internal static string MsgErrorAut {
            get {
                return ResourceManager.GetString("MsgErrorAut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al cambiar la clave.
        /// </summary>
        internal static string MsgErrorCambioPass {
            get {
                return ResourceManager.GetString("MsgErrorCambioPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al cargar los parámetros de la aplicación.
        /// </summary>
        internal static string MsgErrorCargaInicial {
            get {
                return ResourceManager.GetString("MsgErrorCargaInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error creando el cierre del cajero.
        /// </summary>
        internal static string MsgErrorCierreCajero {
            get {
                return ResourceManager.GetString("MsgErrorCierreCajero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error creando el cierre de ventas.
        /// </summary>
        internal static string MsgErrorCierreVentas {
            get {
                return ResourceManager.GetString("MsgErrorCierreVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un cierre de máquina fiscal para la fecha seleccionada.
        /// </summary>
        internal static string MsgErrorCMFDia {
            get {
                return ResourceManager.GetString("MsgErrorCMFDia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de Comunicación con impresora fiscal.
        /// </summary>
        internal static string MsgErrorComImp {
            get {
                return ResourceManager.GetString("MsgErrorComImp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible desactivar la contingencia, ya que la conexión con la DB principal no está activa..
        /// </summary>
        internal static string MsgErrorConexPrinc {
            get {
                return ResourceManager.GetString("MsgErrorConexPrinc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al crear el comprobante.
        /// </summary>
        internal static string MsgErrorCrearComp {
            get {
                return ResourceManager.GetString("MsgErrorCrearComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al desbloquear el usuario.
        /// </summary>
        internal static string MsgErrorDesbloq {
            get {
                return ResourceManager.GetString("MsgErrorDesbloq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al realizar la desactivación de la contingencia..
        /// </summary>
        internal static string MsgErrorFinCont {
            get {
                return ResourceManager.GetString("MsgErrorFinCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al generar el comprobante.
        /// </summary>
        internal static string MsgErrorGenComp {
            get {
                return ResourceManager.GetString("MsgErrorGenComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al generar la nota de crédito.
        /// </summary>
        internal static string MsgErrorGenNC {
            get {
                return ResourceManager.GetString("MsgErrorGenNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener información del comprobante.
        /// </summary>
        internal static string MsgErrorInfoComp {
            get {
                return ResourceManager.GetString("MsgErrorInfoComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al accesar a la aplicación.
        /// </summary>
        internal static string MsgErrorLogin {
            get {
                return ResourceManager.GetString("MsgErrorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al completar la activación de la contingencia.
        /// </summary>
        internal static string MsgErrorParamCont {
            get {
                return ResourceManager.GetString("MsgErrorParamCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al asignar el número de {0}.
        /// </summary>
        internal static string MsgErrorReseed {
            get {
                return ResourceManager.GetString("MsgErrorReseed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tiene registro de caja asociado, no es posible ingresar al sistema.
        /// </summary>
        internal static string MsgErrorSinCaja {
            get {
                return ResourceManager.GetString("MsgErrorSinCaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La impresora no tiene facturación para la fecha seleccionada.
        /// </summary>
        internal static string MsgErrorSinFact {
            get {
                return ResourceManager.GetString("MsgErrorSinFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tiene registro de impresora asociado, no es posible ingresar al sistema.
        /// </summary>
        internal static string MsgErrorSinImpresora {
            get {
                return ResourceManager.GetString("MsgErrorSinImpresora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se realizó con éxito el cierre.
        /// </summary>
        internal static string MsgExitoCierre {
            get {
                return ResourceManager.GetString("MsgExitoCierre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se realizó con éxito el cierre de ventas.
        /// </summary>
        internal static string MsgExitoCierreVentas {
            get {
                return ResourceManager.GetString("MsgExitoCierreVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario desbloqueado exitosamente.
        /// </summary>
        internal static string MsgExitoDesbloq {
            get {
                return ResourceManager.GetString("MsgExitoDesbloq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario desbloqueado exitosamente. Se le cambió la clave a: {0}.
        /// </summary>
        internal static string MsgExitoDesbloqClave {
            get {
                return ResourceManager.GetString("MsgExitoDesbloqClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se requiere autorización para cancelar las facturas en espera.
        /// </summary>
        internal static string MsgFacEsperaCancel {
            get {
                return ResourceManager.GetString("MsgFacEsperaCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizó el tiempo de espera de la factura Nº {0}. Se procederá a cancelar la factura..
        /// </summary>
        internal static string MsgFacEsperaExp {
            get {
                return ResourceManager.GetString("MsgFacEsperaExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impresión de factura cancelada.
        /// </summary>
        internal static string MsgImpCancel {
            get {
                return ResourceManager.GetString("MsgImpCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La impresora no responde. ¿Desea reintentar?.
        /// </summary>
        internal static string MsgImpNoResp {
            get {
                return ResourceManager.GetString("MsgImpNoResp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede ingresar a la aplicación debido a que tiene una sesión abierta en la caja {0}.
        /// </summary>
        internal static string MsgLoginOtraCaja {
            get {
                return ResourceManager.GetString("MsgLoginOtraCaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El monto de apertura no debe exceder {0:C2}.
        /// </summary>
        internal static string MsgMaxApertura {
            get {
                return ResourceManager.GetString("MsgMaxApertura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El monto no debe exceder {0}.
        /// </summary>
        internal static string MsgMontoMax {
            get {
                return ResourceManager.GetString("MsgMontoMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiene Notas de Crédito pendientes, ¿Desea imprimirlas?.
        /// </summary>
        internal static string MsgNCPend {
            get {
                return ResourceManager.GetString("MsgNCPend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario {0} no tiene permiso para autorizar la acción..
        /// </summary>
        internal static string MsgNoEsAutorizador {
            get {
                return ResourceManager.GetString("MsgNoEsAutorizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nuevo password debe ser diferente al anterior.
        /// </summary>
        internal static string MsgNuevoPassDiferente {
            get {
                return ResourceManager.GetString("MsgNuevoPassDiferente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El pago recibido supera al monto total de la factura, Verifique por favor.
        /// </summary>
        internal static string MsgPagoMayorFactura {
            get {
                return ResourceManager.GetString("MsgPagoMayorFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La clave actual es incorrecta.
        /// </summary>
        internal static string MsgPassActual {
            get {
                return ResourceManager.GetString("MsgPassActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea realizar el Cierre de Cajero y Cierre de Caja (Reporte Z)?.
        /// </summary>
        internal static string MsgPregCierreCaja {
            get {
                return ResourceManager.GetString("MsgPregCierreCaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿ Desea realizar el Cierre de Cajero ?.
        /// </summary>
        internal static string MsgPregCierreCajero {
            get {
                return ResourceManager.GetString("MsgPregCierreCajero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿ Desea realizar el Cierre de Ventas ?.
        /// </summary>
        internal static string MsgPregCierreVentas {
            get {
                return ResourceManager.GetString("MsgPregCierreVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuerde que debe haber aprobado los alivios de efectivo para poder contabilizar las cantidades de billetes en los depósitos.
        /// </summary>
        internal static string MsgRecordDep {
            get {
                return ResourceManager.GetString("MsgRecordDep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cierre de Reporte Z fue realizado exitosamente.
        /// </summary>
        internal static string MsgReporteReporteZAutomatico {
            get {
                return ResourceManager.GetString("MsgReporteReporteZAutomatico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe Reporte Z automático pendiente.
        /// </summary>
        internal static string MsgReporteReporteZNOAutomatico {
            get {
                return ResourceManager.GetString("MsgReporteReporteZNOAutomatico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un reporte Z el día de hoy, ¿Desea generar un nuevo reporte Z?.
        /// </summary>
        internal static string MsgReporteZDelDía {
            get {
                return ResourceManager.GetString("MsgReporteZDelDía", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tiene una apertura de caja pendiente por cerrar.
        /// </summary>
        internal static string MsgSinApertura {
            get {
                return ResourceManager.GetString("MsgSinApertura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario {0} ({1}) no ha registrado su entrada en el biométrico.
        /// </summary>
        internal static string MsgSinLectura {
            get {
                return ResourceManager.GetString("MsgSinLectura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte X generado con éxito.
        /// </summary>
        internal static string MsgSucessX {
            get {
                return ResourceManager.GetString("MsgSucessX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte Z generado con éxito.
        /// </summary>
        internal static string MsgSucessZ {
            get {
                return ResourceManager.GetString("MsgSucessZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte mensual detallado generado con éxito.
        /// </summary>
        internal static string MsgSucessZDetallado {
            get {
                return ResourceManager.GetString("MsgSucessZDetallado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte mensual consolidado generado con éxito.
        /// </summary>
        internal static string MsgSucessZMensual {
            get {
                return ResourceManager.GetString("MsgSucessZMensual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reportes de Z por rangos generado con éxito.
        /// </summary>
        internal static string MsgSucessZRango {
            get {
                return ResourceManager.GetString("MsgSucessZRango", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizaron los primeros cinco (5) minutos en espera, ¿Desea recuperar la factura?.
        /// </summary>
        internal static string MsgTieneFacEspera {
            get {
                return ResourceManager.GetString("MsgTieneFacEspera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario {0} bloqueado.
        /// </summary>
        internal static string MsgUsuarioBloqueado {
            get {
                return ResourceManager.GetString("MsgUsuarioBloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario {0} ({1}) no tiene acceso a la aplicacion.
        /// </summary>
        internal static string MsgUsuarioNoApp {
            get {
                return ResourceManager.GetString("MsgUsuarioNoApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario &apos;{0}&apos; no encontrado.
        /// </summary>
        internal static string MsgUsuarioNoExiste {
            get {
                return ResourceManager.GetString("MsgUsuarioNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha desde debe ser menor o igual a fecha hasta.
        /// </summary>
        internal static string MsgValidacionFecha {
            get {
                return ResourceManager.GetString("MsgValidacionFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número Z desde debe ser menor que número Z hasta.
        /// </summary>
        internal static string MsgValidacionRango {
            get {
                return ResourceManager.GetString("MsgValidacionRango", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap notadecredito {
            get {
                object obj = ResourceManager.GetObject("notadecredito", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pedidosugerido {
            get {
                object obj = ResourceManager.GetObject("pedidosugerido", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap procesar {
            get {
                object obj = ResourceManager.GetObject("procesar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap progreso {
            get {
                object obj = ResourceManager.GetObject("progreso", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excedio el maximo de intentos.
        /// </summary>
        internal static string ReasonLocked {
            get {
                return ResourceManager.GetString("ReasonLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap red {
            get {
                object obj = ResourceManager.GetObject("red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refrescar {
            get {
                object obj = ResourceManager.GetObject("refrescar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refrescarpeq {
            get {
                object obj = ResourceManager.GetObject("refrescarpeq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} registros encontrados..
        /// </summary>
        internal static string RegEncontrados {
            get {
                return ResourceManager.GetString("RegEncontrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap reimprimir {
            get {
                object obj = ResourceManager.GetObject("reimprimir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReporteZ {
            get {
                object obj = ResourceManager.GetObject("ReporteZ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap reposisionarticulos {
            get {
                object obj = ResourceManager.GetObject("reposisionarticulos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rojo {
            get {
                object obj = ResourceManager.GetObject("Rojo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap salir {
            get {
                object obj = ResourceManager.GetObject("salir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap separador {
            get {
                object obj = ResourceManager.GetObject("separador", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap separadorh {
            get {
                object obj = ResourceManager.GetObject("separadorh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap siguienteenespera {
            get {
                object obj = ResourceManager.GetObject("siguienteenespera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar forma de pago.
        /// </summary>
        internal static string TipAgregarFP {
            get {
                return ResourceManager.GetString("TipAgregarFP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloquear sesión (F6).
        /// </summary>
        internal static string TipBloquear {
            get {
                return ResourceManager.GetString("TipBloquear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscador de Artículos.
        /// </summary>
        internal static string TipBuscarArt {
            get {
                return ResourceManager.GetString("TipBuscarArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Cliente (F2).
        /// </summary>
        internal static string TipBuscarCliente {
            get {
                return ResourceManager.GetString("TipBuscarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculadora.
        /// </summary>
        internal static string TipCalc {
            get {
                return ResourceManager.GetString("TipCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        internal static string TipCerrar {
            get {
                return ResourceManager.GetString("TipCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar Sesión.
        /// </summary>
        internal static string TipSalir {
            get {
                return ResourceManager.GetString("TipSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar Vendedor.
        /// </summary>
        internal static string TipSelVendedor {
            get {
                return ResourceManager.GetString("TipSelVendedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Foto.
        /// </summary>
        internal static string TipVerFoto {
            get {
                return ResourceManager.GetString("TipVerFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unlock {
            get {
                object obj = ResourceManager.GetObject("unlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap usuario {
            get {
                object obj = ResourceManager.GetObject("usuario", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe cargar la imagen.
        /// </summary>
        internal static string ValCargarImagen {
            get {
                return ResourceManager.GetString("ValCargarImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La clave debe ser de al menos 6 caracteres y contener letras y números.
        /// </summary>
        internal static string ValClaveCompleja {
            get {
                return ResourceManager.GetString("ValClaveCompleja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La clave no debe contener su login.
        /// </summary>
        internal static string ValClaveNoLogin {
            get {
                return ResourceManager.GetString("ValClaveNoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar la factura sustituta.
        /// </summary>
        internal static string ValFactSust {
            get {
                return ResourceManager.GetString("ValFactSust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar la imagen del ticket fiscal.
        /// </summary>
        internal static string ValImagenTicket {
            get {
                return ResourceManager.GetString("ValImagenTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar al menos uno de los criterios marcados.
        /// </summary>
        internal static string ValIngrese1Crit {
            get {
                return ResourceManager.GetString("ValIngrese1Crit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el apellido.
        /// </summary>
        internal static string ValIngreseApellido {
            get {
                return ResourceManager.GetString("ValIngreseApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese la dirección.
        /// </summary>
        internal static string ValIngreseDirecc {
            get {
                return ResourceManager.GetString("ValIngreseDirecc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el documento.
        /// </summary>
        internal static string ValIngreseDoc {
            get {
                return ResourceManager.GetString("ValIngreseDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el email.
        /// </summary>
        internal static string ValIngreseEmail {
            get {
                return ResourceManager.GetString("ValIngreseEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el monto.
        /// </summary>
        internal static string ValIngreseMonto {
            get {
                return ResourceManager.GetString("ValIngreseMonto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el nombre.
        /// </summary>
        internal static string ValIngreseNombre {
            get {
                return ResourceManager.GetString("ValIngreseNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese la nueva clave.
        /// </summary>
        internal static string ValIngreseNuevoPass {
            get {
                return ResourceManager.GetString("ValIngreseNuevoPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar un número de factura o de documento del cliente.
        /// </summary>
        internal static string ValIngreseNumeroODoc {
            get {
                return ResourceManager.GetString("ValIngreseNumeroODoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe llenar las observaciones.
        /// </summary>
        internal static string ValIngreseObs {
            get {
                return ResourceManager.GetString("ValIngreseObs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese la clave actual.
        /// </summary>
        internal static string ValIngresePassActual {
            get {
                return ResourceManager.GetString("ValIngresePassActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese la clave.
        /// </summary>
        internal static string ValIngresePassword {
            get {
                return ResourceManager.GetString("ValIngresePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese la razón social.
        /// </summary>
        internal static string ValIngreseRazonSoc {
            get {
                return ResourceManager.GetString("ValIngreseRazonSoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el usuario.
        /// </summary>
        internal static string ValIngreseUsuario {
            get {
                return ResourceManager.GetString("ValIngreseUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar el valor.
        /// </summary>
        internal static string ValIngreseValor {
            get {
                return ResourceManager.GetString("ValIngreseValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Nro. de Lote es requerido para las formas de pago Débito y Crédito.
        /// </summary>
        internal static string ValLoteReq {
            get {
                return ResourceManager.GetString("ValLoteReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar un mínimo de {0} caracteres.
        /// </summary>
        internal static string ValMinCar {
            get {
                return ResourceManager.GetString("ValMinCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El monto del cierre debe mayor que cero.
        /// </summary>
        internal static string ValMontoCierre {
            get {
                return ResourceManager.GetString("ValMontoCierre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El monto no es válido.
        /// </summary>
        internal static string ValMontoNoVal {
            get {
                return ResourceManager.GetString("ValMontoNoVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Monto de las transacciones.
        /// </summary>
        internal static string ValMontoReq {
            get {
                return ResourceManager.GetString("ValMontoReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar el motivo de Solicitud de Nota de Crédito.
        /// </summary>
        internal static string ValMotivoSolNC {
            get {
                return ResourceManager.GetString("ValMotivoSolNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La nueva clave no coincide.
        /// </summary>
        internal static string ValNuevoPassNoMatch {
            get {
                return ResourceManager.GetString("ValNuevoPassNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el número de comprobante.
        /// </summary>
        internal static string ValNumComp {
            get {
                return ResourceManager.GetString("ValNumComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el número de depósito.
        /// </summary>
        internal static string ValNumDep {
            get {
                return ResourceManager.GetString("ValNumDep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el número del envase.
        /// </summary>
        internal static string ValNumEnvase {
            get {
                return ResourceManager.GetString("ValNumEnvase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de {0} no debe ser menor al actual ({1}).
        /// </summary>
        internal static string ValNumeroReseed {
            get {
                return ResourceManager.GetString("ValNumeroReseed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Nro. de Lote debe estar entre {0} y {1}.
        /// </summary>
        internal static string ValRangoLote {
            get {
                return ResourceManager.GetString("ValRangoLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar al menos 4 caracteres de la referencia.
        /// </summary>
        internal static string ValRef4 {
            get {
                return ResourceManager.GetString("ValRef4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repita la nueva clave.
        /// </summary>
        internal static string ValRepitaNuevoPass {
            get {
                return ResourceManager.GetString("ValRepitaNuevoPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el banco.
        /// </summary>
        internal static string ValSelBanco {
            get {
                return ResourceManager.GetString("ValSelBanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el banco emisor.
        /// </summary>
        internal static string ValSelBancoEm {
            get {
                return ResourceManager.GetString("ValSelBancoEm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el banco del POS.
        /// </summary>
        internal static string ValSelBancoPOS {
            get {
                return ResourceManager.GetString("ValSelBancoPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar una colección.
        /// </summary>
        internal static string ValSelColec {
            get {
                return ResourceManager.GetString("ValSelColec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar el esquema.
        /// </summary>
        internal static string ValSelEsquema {
            get {
                return ResourceManager.GetString("ValSelEsquema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione la forma de pago.
        /// </summary>
        internal static string ValSelFormaPago {
            get {
                return ResourceManager.GetString("ValSelFormaPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el POS.
        /// </summary>
        internal static string ValSelPOS {
            get {
                return ResourceManager.GetString("ValSelPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el usuario responsable del conteo.
        /// </summary>
        internal static string ValSelResp {
            get {
                return ResourceManager.GetString("ValSelResp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vendedor {
            get {
                object obj = ResourceManager.GetObject("vendedor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ventasdia {
            get {
                object obj = ResourceManager.GetObject("ventasdia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ventasporarticulo {
            get {
                object obj = ResourceManager.GetObject("ventasporarticulo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Verde {
            get {
                object obj = ResourceManager.GetObject("Verde", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap view {
            get {
                object obj = ResourceManager.GetObject("view", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap viewpeq {
            get {
                object obj = ResourceManager.GetObject("viewpeq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap warning32 {
            get {
                object obj = ResourceManager.GetObject("warning32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap yellow {
            get {
                object obj = ResourceManager.GetObject("yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
